---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hehehemann for Vehicle Repair Overhaul Build42.
--- DateTime: 2/29/2022 11:10 PM
---
---Quick list to allow the mechanic repair option to be set enabled for all vehicle parts---
---
require "Vehicles/ISUI/ISVehicleMechanics"

local enableRepairs = ISVehicleMechanics.doPartContextMenu

function ISVehicleMechanics:doPartContextMenu(part, x, y)
    -- Game speed check (Remove -- if you do not want the vehicle menu to show when game is paused)
    -- if UIManager.getSpeedControls():getCurrentGameSpeed() == 0 then return end

    -- Player and vehicle validation
    local playerObj = getSpecificPlayer(self.playerNum)
    if playerObj:getVehicle() ~= nil and not (isDebugEnabled() or (isClient() and (isAdmin() or getAccessLevel() == "moderator"))) then
        return
    end

    -- Create context menu
    self.context = ISContextMenu.get(self.playerNum, x + self:getAbsoluteX(), y + self:getAbsoluteY())

    -- Custom repair mechanic logic
    if (part:getId() == ("GloveBox") or ("Heater") or ("Battery") or ("Brake") or ("Door") or ("EngineDoor") or
            ("GasTank") or ("Tire") or ("Trunk") or ("TrunkDoor") or ("Headlight") or ("Seat") or ("Window)") or
            ("Muffler") or ("Radio") or ("Suspension") or ("Windshield") or ("TowBar") or ("lightbar"))then
	if part:getCondition() < 100 then
        part:getScriptPart():setRepairMechanic(true)
    elseif part:getCondition() == 100 and part:getScriptPart():isRepairMechanic() then
        part:getScriptPart():setRepairMechanic(false)
    end

    -- Call the original function for compatibility with other mods
    enableRepairs(self, part, x, y)
    end
end