SpriteDimensions = SpriteDimensions or {}




SpriteDimensions.default = {
    -- this value will multiply the chanceOnFurniture or the chanceOnFloor.
    chanceModifier = 1,

    -- Where on the tile the item will be spawned
    -- (the mod takes ZombRand(minOffsetX, maxOffsetX) for the x position and ZombRand(minOffsetY, maxOffsetY) for y position)
    -- avoid the edges to not spawn items levitating in the air!
    minOffsetX = 35,
    maxOffsetX = 65,
    minOffsetY = 35,
    maxOffsetY = 65,
}

SpriteDimensions.defaultOnFloor = {
    chanceModifier = 1,
    minOffsetX = 15,
    maxOffsetX = 85,
    minOffsetY = 15,
    maxOffsetY = 85,
}


SpriteDimensions.middle = {
    minOffsetX = 35,
    maxOffsetX = 65,
    minOffsetY = 35,
    maxOffsetY = 65,
}


SpriteDimensions.ThreeQuartersNorth = {
    minOffsetX = 10,
    maxOffsetX = 90,
    minOffsetY = 10,
    maxOffsetY = 65,
}
SpriteDimensions.ThreeQuartersSouth = {
    minOffsetX = 70,
    maxOffsetX = 90,
    minOffsetY = 35,
    maxOffsetY = 90,
}
SpriteDimensions.ThreeQuartersWest = {
    minOffsetX = 10,
    maxOffsetX = 65,
    minOffsetY = 10,
    maxOffsetY = 90,
}
SpriteDimensions.ThreeQuartersEast = {
    minOffsetX = 35,
    maxOffsetX = 90,
    minOffsetY = 10,
    maxOffsetY = 90,
}


SpriteDimensions.HalfNorth = {
    minOffsetX = 10,
    maxOffsetX = 90,
    minOffsetY = 10,
    maxOffsetY = 45,
}
SpriteDimensions.HalfSouth = {
    minOffsetX = 10,
    maxOffsetX = 90,
    minOffsetY = 55,
    maxOffsetY = 90,
}
SpriteDimensions.HalfWest = {
    minOffsetX = 10,
    maxOffsetX = 45,
    minOffsetY = 10,
    maxOffsetY = 90,
}
SpriteDimensions.HalfEast = {
    minOffsetX = 55,
    maxOffsetX = 90,
    minOffsetY = 10,
    maxOffsetY = 90,
}


SpriteDimensions.MiddleSmall = {
    minOffsetX = 40,
    maxOffsetX = 60,
    minOffsetY = 40,
    maxOffsetY = 60,
}

SpriteDimensions.MiddleLarge = {
    minOffsetX = 10,
    maxOffsetX = 90,
    minOffsetY = 10,
    maxOffsetY = 90,
}

SpriteDimensions.MiddleLongX = {
    minOffsetX = 10,
    maxOffsetX = 90,
    minOffsetY = 40,
    maxOffsetY = 60,
}
SpriteDimensions.MiddleLongY = {
    minOffsetX = 40,
    maxOffsetX = 60,
    minOffsetY = 10,
    maxOffsetY = 90,
}


SpriteDimensions.list = {
   fixtures_counters_01_4 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_5 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_6 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_12 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_13 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_14 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_36 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_37 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_38 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_52 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_53 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_54 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_60 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_61 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_62 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_68 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_69 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_70 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_76 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_77 = SpriteDimensions.ThreeQuartersNorth,
   fixtures_counters_01_78 = SpriteDimensions.ThreeQuartersNorth,

   appliances_cooking_01_42= SpriteDimensions.ThreeQuartersNorth,
   appliances_cooking_01_43= SpriteDimensions.ThreeQuartersNorth,

   appliances_cooking_01_1= SpriteDimensions.ThreeQuartersNorth,
   appliances_cooking_01_5= SpriteDimensions.ThreeQuartersNorth,
   appliances_cooking_01_9= SpriteDimensions.ThreeQuartersNorth,
   appliances_cooking_01_13= SpriteDimensions.ThreeQuartersNorth,
   appliances_cooking_01_17= SpriteDimensions.ThreeQuartersNorth,
   appliances_cooking_01_21= SpriteDimensions.ThreeQuartersNorth,
   appliances_cooking_01_53= SpriteDimensions.ThreeQuartersNorth,
   appliances_cooking_01_65= SpriteDimensions.ThreeQuartersNorth,

   appliances_refrigeration_01_0= SpriteDimensions.ThreeQuartersNorth,
   appliances_refrigeration_01_4= SpriteDimensions.ThreeQuartersNorth,
   appliances_refrigeration_01_8= SpriteDimensions.ThreeQuartersNorth,
   appliances_refrigeration_01_12= SpriteDimensions.ThreeQuartersNorth,
   appliances_refrigeration_01_28= SpriteDimensions.ThreeQuartersNorth,
   appliances_refrigeration_01_32= SpriteDimensions.ThreeQuartersNorth,
   appliances_refrigeration_01_40= SpriteDimensions.ThreeQuartersNorth,
   appliances_refrigeration_01_22= SpriteDimensions.ThreeQuartersNorth,
   appliances_refrigeration_01_18= SpriteDimensions.ThreeQuartersNorth,
   appliances_refrigeration_01_19= SpriteDimensions.ThreeQuartersNorth,


   furniture_storage_02_0= SpriteDimensions.ThreeQuartersNorth,
   location_shop_accessories_01_17= SpriteDimensions.ThreeQuartersNorth,
   location_shop_accessories_01_19= SpriteDimensions.ThreeQuartersNorth,
   
   location_shop_generic_01_100= SpriteDimensions.ThreeQuartersNorth,
   location_shop_generic_01_101= SpriteDimensions.ThreeQuartersNorth,
   location_shop_generic_01_102= SpriteDimensions.ThreeQuartersNorth,
   location_shop_generic_01_20= SpriteDimensions.ThreeQuartersNorth,
   location_shop_generic_01_21= SpriteDimensions.ThreeQuartersNorth,
   location_shop_generic_01_22= SpriteDimensions.ThreeQuartersNorth,

   location_trailer_02_18= SpriteDimensions.ThreeQuartersNorth,
   location_trailer_02_16= SpriteDimensions.ThreeQuartersNorth,

   location_restaurant_bar_01_4 = SpriteDimensions.ThreeQuartersNorth,
   location_restaurant_bar_01_5 = SpriteDimensions.ThreeQuartersNorth,
   location_restaurant_bar_01_6 = SpriteDimensions.ThreeQuartersNorth,
   location_restaurant_bar_01_20 = SpriteDimensions.ThreeQuartersNorth,
   location_restaurant_bar_01_21 = SpriteDimensions.ThreeQuartersNorth,
   location_restaurant_bar_01_22 = SpriteDimensions.ThreeQuartersNorth,
   location_restaurant_bar_01_60 = SpriteDimensions.ThreeQuartersNorth,
   location_restaurant_bar_01_61 = SpriteDimensions.ThreeQuartersNorth,
   location_restaurant_bar_01_62 = SpriteDimensions.ThreeQuartersNorth,


   fixtures_counters_01_0 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_1 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_2 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_8 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_9 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_10 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_32 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_33 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_34 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_40 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_41 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_42 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_48 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_49 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_50 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_56 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_57 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_58 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_64 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_65 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_66 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_72 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_73 = SpriteDimensions.ThreeQuartersSouth,
   fixtures_counters_01_74 = SpriteDimensions.ThreeQuartersSouth,
   appliances_cooking_01_50= SpriteDimensions.ThreeQuartersSouth,
   appliances_cooking_01_51= SpriteDimensions.ThreeQuartersSouth,

   appliances_cooking_01_3= SpriteDimensions.ThreeQuartersSouth,
   appliances_cooking_01_7= SpriteDimensions.ThreeQuartersSouth,
   appliances_cooking_01_11= SpriteDimensions.ThreeQuartersSouth,
   appliances_cooking_01_15= SpriteDimensions.ThreeQuartersSouth,
   appliances_cooking_01_19= SpriteDimensions.ThreeQuartersSouth,
   appliances_cooking_01_23= SpriteDimensions.ThreeQuartersSouth,
   appliances_cooking_01_55= SpriteDimensions.ThreeQuartersSouth,
   appliances_cooking_01_67= SpriteDimensions.ThreeQuartersSouth,
    
   appliances_refrigeration_01_2= SpriteDimensions.ThreeQuartersSouth,
   appliances_refrigeration_01_6= SpriteDimensions.ThreeQuartersSouth,
   appliances_refrigeration_01_10= SpriteDimensions.ThreeQuartersSouth,
   appliances_refrigeration_01_14= SpriteDimensions.ThreeQuartersSouth,
   appliances_refrigeration_01_30= SpriteDimensions.ThreeQuartersSouth,
   appliances_refrigeration_01_34= SpriteDimensions.ThreeQuartersSouth,
   appliances_refrigeration_01_36= SpriteDimensions.ThreeQuartersSouth,
   appliances_refrigeration_01_42= SpriteDimensions.ThreeQuartersSouth,
   appliances_refrigeration_01_46= SpriteDimensions.ThreeQuartersSouth,
   appliances_refrigeration_01_47= SpriteDimensions.ThreeQuartersSouth,

   
   location_shop_accessories_01_29= SpriteDimensions.ThreeQuartersSouth,
   location_shop_accessories_01_31= SpriteDimensions.ThreeQuartersSouth,
   
   furniture_storage_02_3= SpriteDimensions.ThreeQuartersSouth,
   location_shop_generic_01_96= SpriteDimensions.ThreeQuartersSouth,
   location_shop_generic_01_97= SpriteDimensions.ThreeQuartersSouth,
   location_shop_generic_01_98= SpriteDimensions.ThreeQuartersSouth,
   location_shop_generic_01_16= SpriteDimensions.ThreeQuartersSouth,
   location_shop_generic_01_17= SpriteDimensions.ThreeQuartersSouth,
   location_shop_generic_01_18= SpriteDimensions.ThreeQuartersSouth,

   location_trailer_02_10= SpriteDimensions.ThreeQuartersSouth,
   location_trailer_02_20= SpriteDimensions.ThreeQuartersSouth,
   

   location_restaurant_bar_01_0 = SpriteDimensions.ThreeQuartersSouth,
   location_restaurant_bar_01_1 = SpriteDimensions.ThreeQuartersSouth,
   location_restaurant_bar_01_2 = SpriteDimensions.ThreeQuartersSouth,
   location_restaurant_bar_01_16 = SpriteDimensions.ThreeQuartersSouth,
   location_restaurant_bar_01_17 = SpriteDimensions.ThreeQuartersSouth,
   location_restaurant_bar_01_18 = SpriteDimensions.ThreeQuartersSouth,
   location_restaurant_bar_01_56 = SpriteDimensions.ThreeQuartersSouth,
   location_restaurant_bar_01_57 = SpriteDimensions.ThreeQuartersSouth,
   location_restaurant_bar_01_58 = SpriteDimensions.ThreeQuartersSouth,


   fixtures_counters_01_03 = SpriteDimensions.ThreeQuartersWest,
   fixtures_counters_01_11 = SpriteDimensions.ThreeQuartersWest,
   fixtures_counters_01_35 = SpriteDimensions.ThreeQuartersWest,
   fixtures_counters_01_43 = SpriteDimensions.ThreeQuartersWest,
   fixtures_counters_01_51 = SpriteDimensions.ThreeQuartersWest,
   fixtures_counters_01_59 = SpriteDimensions.ThreeQuartersWest,
   fixtures_counters_01_67 = SpriteDimensions.ThreeQuartersWest,
   fixtures_counters_01_75 = SpriteDimensions.ThreeQuartersWest,
   appliances_cooking_01_40= SpriteDimensions.ThreeQuartersWest,
   appliances_cooking_01_41= SpriteDimensions.ThreeQuartersWest,
   
   appliances_cooking_01_0= SpriteDimensions.ThreeQuartersWest,
   appliances_cooking_01_4= SpriteDimensions.ThreeQuartersWest,
   appliances_cooking_01_8= SpriteDimensions.ThreeQuartersWest,
   appliances_cooking_01_12= SpriteDimensions.ThreeQuartersWest,
   appliances_cooking_01_16= SpriteDimensions.ThreeQuartersWest,
   appliances_cooking_01_20= SpriteDimensions.ThreeQuartersWest,
   appliances_cooking_01_52= SpriteDimensions.ThreeQuartersWest,
   appliances_cooking_01_64= SpriteDimensions.ThreeQuartersWest,

   appliances_refrigeration_01_1= SpriteDimensions.ThreeQuartersWest,
   appliances_refrigeration_01_5= SpriteDimensions.ThreeQuartersWest,
   appliances_refrigeration_01_9= SpriteDimensions.ThreeQuartersWest,
   appliances_refrigeration_01_13= SpriteDimensions.ThreeQuartersWest,
   appliances_refrigeration_01_16= SpriteDimensions.ThreeQuartersWest,
   appliances_refrigeration_01_17= SpriteDimensions.ThreeQuartersWest,
   appliances_refrigeration_01_23= SpriteDimensions.ThreeQuartersWest,
   appliances_refrigeration_01_29= SpriteDimensions.ThreeQuartersWest,
   appliances_refrigeration_01_33= SpriteDimensions.ThreeQuartersWest,
   appliances_refrigeration_01_41= SpriteDimensions.ThreeQuartersWest,

   furniture_storage_02_1= SpriteDimensions.ThreeQuartersWest,
   location_shop_accessories_01_16= SpriteDimensions.ThreeQuartersWest,
   location_shop_accessories_01_18= SpriteDimensions.ThreeQuartersWest,
   location_shop_generic_01_99= SpriteDimensions.ThreeQuartersWest,
   location_shop_generic_01_19= SpriteDimensions.ThreeQuartersWest,
   
   location_trailer_02_17= SpriteDimensions.ThreeQuartersWest,
   location_trailer_02_19= SpriteDimensions.ThreeQuartersWest,
   
   location_restaurant_bar_01_3 = SpriteDimensions.ThreeQuartersWest,
   location_restaurant_bar_01_19 = SpriteDimensions.ThreeQuartersWest,
   location_restaurant_bar_01_59 = SpriteDimensions.ThreeQuartersWest,

   fixtures_counters_01_07 = SpriteDimensions.ThreeQuartersEast,
   fixtures_counters_01_15 = SpriteDimensions.ThreeQuartersEast,
   fixtures_counters_01_39 = SpriteDimensions.ThreeQuartersEast,
   fixtures_counters_01_47= SpriteDimensions.ThreeQuartersEast,
   fixtures_counters_01_55= SpriteDimensions.ThreeQuartersEast,
   fixtures_counters_01_63= SpriteDimensions.ThreeQuartersEast,
   fixtures_counters_01_71= SpriteDimensions.ThreeQuartersEast,
   fixtures_counters_01_79= SpriteDimensions.ThreeQuartersEast,
   appliances_cooking_01_48= SpriteDimensions.ThreeQuartersEast,
   appliances_cooking_01_49= SpriteDimensions.ThreeQuartersEast,
   
   appliances_cooking_01_2= SpriteDimensions.ThreeQuartersEast,
   appliances_cooking_01_6= SpriteDimensions.ThreeQuartersEast,
   appliances_cooking_01_10= SpriteDimensions.ThreeQuartersEast,
   appliances_cooking_01_14= SpriteDimensions.ThreeQuartersEast,
   appliances_cooking_01_18= SpriteDimensions.ThreeQuartersEast,
   appliances_cooking_01_22= SpriteDimensions.ThreeQuartersEast,
   appliances_cooking_01_54= SpriteDimensions.ThreeQuartersEast,
   appliances_cooking_01_66= SpriteDimensions.ThreeQuartersEast,

   appliances_refrigeration_01_3= SpriteDimensions.ThreeQuartersEast,
   appliances_refrigeration_01_7= SpriteDimensions.ThreeQuartersEast,
   appliances_refrigeration_01_11= SpriteDimensions.ThreeQuartersEast,
   appliances_refrigeration_01_15= SpriteDimensions.ThreeQuartersEast,
   appliances_refrigeration_01_31= SpriteDimensions.ThreeQuartersEast,
   appliances_refrigeration_01_35= SpriteDimensions.ThreeQuartersEast,
   appliances_refrigeration_01_37= SpriteDimensions.ThreeQuartersEast,
   appliances_refrigeration_01_43= SpriteDimensions.ThreeQuartersEast,
   appliances_refrigeration_01_44= SpriteDimensions.ThreeQuartersEast,
   appliances_refrigeration_01_45= SpriteDimensions.ThreeQuartersEast,

   furniture_storage_02_2= SpriteDimensions.ThreeQuartersEast,
   location_shop_accessories_01_28= SpriteDimensions.ThreeQuartersEast,
   location_shop_accessories_01_30= SpriteDimensions.ThreeQuartersEast,
   location_shop_generic_01_103= SpriteDimensions.ThreeQuartersEast,
   location_shop_generic_01_23= SpriteDimensions.ThreeQuartersEast,
   
   location_trailer_02_11= SpriteDimensions.ThreeQuartersEast,
   location_trailer_02_21= SpriteDimensions.ThreeQuartersEast,

   location_restaurant_bar_01_7 = SpriteDimensions.ThreeQuartersEast,
   location_restaurant_bar_01_23 = SpriteDimensions.ThreeQuartersEast,
   location_restaurant_bar_01_63 = SpriteDimensions.ThreeQuartersEast,

   appliances_refrigeration_01_24= SpriteDimensions.MiddleSmall,
   appliances_refrigeration_01_25= SpriteDimensions.MiddleSmall,
   appliances_refrigeration_01_26= SpriteDimensions.MiddleSmall,
   appliances_refrigeration_01_27= SpriteDimensions.MiddleSmall,
   location_business_office_generic_01_32= SpriteDimensions.MiddleSmall,
   location_business_office_generic_01_33= SpriteDimensions.MiddleSmall,
   location_business_office_generic_01_34= SpriteDimensions.MiddleSmall,
   location_business_office_generic_01_35= SpriteDimensions.MiddleSmall,
   location_business_office_generic_01_16= SpriteDimensions.MiddleSmall,
   location_business_office_generic_01_17= SpriteDimensions.MiddleSmall,
   location_business_office_generic_01_24= SpriteDimensions.MiddleSmall,
   location_business_office_generic_01_25= SpriteDimensions.MiddleSmall,
   furniture_tables_low_01_2= SpriteDimensions.MiddleSmall,
   furniture_tables_low_01_3= SpriteDimensions.MiddleSmall,
   furniture_tables_low_01_4= SpriteDimensions.MiddleSmall,
   furniture_tables_low_01_5= SpriteDimensions.MiddleSmall,
   furniture_tables_low_01_6= SpriteDimensions.MiddleSmall,
   furniture_tables_low_01_7= SpriteDimensions.MiddleSmall,
   location_community_medical_01_48= SpriteDimensions.MiddleSmall,
   location_community_medical_01_49= SpriteDimensions.MiddleSmall,
   location_community_medical_01_50= SpriteDimensions.MiddleSmall,
   location_community_medical_01_51= SpriteDimensions.MiddleSmall,

    furniture_seating_indoor_01_0 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_1 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_2 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_3 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_4 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_5 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_6 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_7 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_8 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_9 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_10 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_11 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_12 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_13 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_14 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_15 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_16 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_17 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_18 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_19 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_20 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_21 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_22 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_23 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_24 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_25 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_26 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_27 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_28 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_29 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_30 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_31 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_32 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_33 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_34 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_35 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_36 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_37 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_38 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_39 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_40 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_41 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_42 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_43 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_44 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_45 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_46 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_47 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_48 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_49 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_50 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_51 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_52 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_53 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_54 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_55 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_56 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_57 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_58 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_59 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_60 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_61 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_62 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_01_63 = SpriteDimensions.MiddleSmall,

    furniture_seating_indoor_02_0 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_1 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_2 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_3 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_4 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_5 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_6 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_7 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_8 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_9 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_10 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_11 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_12 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_13 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_14 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_15 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_16 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_17 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_18 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_19 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_20 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_21 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_22 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_23 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_24 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_25 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_26 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_27 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_28 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_29 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_30 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_31 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_32 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_33 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_34 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_35 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_36 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_37 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_38 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_39 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_40 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_41 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_42 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_43 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_44 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_45 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_46 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_47 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_48 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_49 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_50 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_51 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_52 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_53 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_54 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_55 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_56 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_57 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_58 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_59 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_60 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_61 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_62 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_02_63 = SpriteDimensions.MiddleSmall,

    furniture_seating_indoor_03_0 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_1 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_2 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_3 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_4 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_5 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_6 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_7 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_8 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_9 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_10 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_11 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_12 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_13 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_14 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_15 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_16 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_17 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_18 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_19 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_20 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_21 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_22 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_23 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_24 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_25 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_26 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_27 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_28 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_29 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_30 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_31 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_32 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_33 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_34 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_35 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_36 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_37 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_38 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_39 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_40 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_41 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_42 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_43 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_44 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_45 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_46 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_47 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_48 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_49 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_50 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_51 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_52 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_53 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_54 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_55 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_56 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_57 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_58 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_59 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_60 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_61 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_62 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_63 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_64 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_65 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_66 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_67 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_68 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_69 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_70 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_71 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_72 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_73 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_74 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_75 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_76 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_77 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_78 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_79 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_80 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_81 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_82 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_83 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_84 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_85 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_86 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_87 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_88 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_89 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_90 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_91 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_92 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_93 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_94 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_95 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_96 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_97 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_98 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_99 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_100 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_101 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_102 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_103 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_104 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_105 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_106 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_107 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_108 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_109 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_110 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_111 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_112 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_113 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_114 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_115 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_116 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_117 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_118 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_119 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_120 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_121 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_122 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_123 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_124 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_125 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_126 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_127 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_128 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_129 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_130 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_131 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_132 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_133 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_134 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_135 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_136 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_137 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_138 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_139 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_140 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_141 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_142 = SpriteDimensions.MiddleSmall,
    furniture_seating_indoor_03_143 = SpriteDimensions.MiddleSmall,
    furniture_seating_outdoor_01_16 = SpriteDimensions.MiddleSmall,
    furniture_seating_outdoor_01_17 = SpriteDimensions.MiddleSmall,
    furniture_seating_outdoor_01_18 = SpriteDimensions.MiddleSmall,
    furniture_seating_outdoor_01_19 = SpriteDimensions.MiddleSmall,
    
    furniture_storage_01_52 = SpriteDimensions.MiddleSmall,
    furniture_storage_01_53 = SpriteDimensions.MiddleSmall,
    furniture_storage_01_54 = SpriteDimensions.MiddleSmall,
    furniture_storage_01_55 = SpriteDimensions.MiddleSmall,
    location_restaurant_bar_01_25 = SpriteDimensions.MiddleSmall,
    location_restaurant_bar_01_26 = SpriteDimensions.MiddleSmall,
    location_community_medical_01_10= SpriteDimensions.MiddleSmall,

   furniture_shelving_01_0= SpriteDimensions.HalfNorth,
   furniture_shelving_01_1= SpriteDimensions.HalfNorth,
   furniture_shelving_01_8= SpriteDimensions.HalfNorth,
   furniture_shelving_01_9= SpriteDimensions.HalfNorth,
   furniture_shelving_01_16= SpriteDimensions.HalfNorth,
   furniture_shelving_01_17= SpriteDimensions.HalfNorth,
   furniture_shelving_01_18= SpriteDimensions.HalfNorth,
   furniture_shelving_01_19= SpriteDimensions.HalfNorth,
   furniture_shelving_01_28= SpriteDimensions.HalfNorth,
   furniture_shelving_01_33= SpriteDimensions.HalfNorth,
   furniture_shelving_01_35= SpriteDimensions.HalfNorth,
   furniture_shelving_01_37= SpriteDimensions.HalfNorth,
   furniture_shelving_01_40= SpriteDimensions.HalfNorth,
   furniture_shelving_01_44= SpriteDimensions.HalfNorth,
   furniture_storage_02_8= SpriteDimensions.HalfNorth,
   location_restaurant_generic_01_0= SpriteDimensions.HalfNorth,
   location_restaurant_generic_01_2= SpriteDimensions.HalfNorth,
   location_restaurant_generic_01_8= SpriteDimensions.HalfNorth,
   location_restaurant_generic_01_10= SpriteDimensions.HalfNorth,
   location_shop_generic_01_2= SpriteDimensions.HalfNorth,
   location_shop_generic_01_30= SpriteDimensions.HalfNorth,
   location_shop_generic_01_34= SpriteDimensions.HalfNorth,
   location_shop_generic_01_35= SpriteDimensions.HalfNorth,
   location_shop_generic_01_62= SpriteDimensions.HalfNorth,
   location_shop_generic_01_64= SpriteDimensions.HalfNorth,
   location_shop_generic_01_65= SpriteDimensions.HalfNorth,
   location_shop_generic_01_66= SpriteDimensions.HalfNorth,
   location_shop_generic_01_72= SpriteDimensions.HalfNorth,
   location_shop_generic_01_73= SpriteDimensions.HalfNorth,
   location_shop_generic_01_80= SpriteDimensions.HalfNorth,
   location_shop_generic_01_81= SpriteDimensions.HalfNorth,
   location_shop_generic_01_82= SpriteDimensions.HalfNorth,
   location_shop_generic_01_86= SpriteDimensions.HalfNorth,
   location_shop_generic_01_92= SpriteDimensions.HalfNorth,

   recreational_01_8= SpriteDimensions.HalfNorth,
   recreational_01_9= SpriteDimensions.HalfNorth,
   location_restaurant_bar_01_8 = SpriteDimensions.HalfNorth,
   location_restaurant_bar_01_9 = SpriteDimensions.HalfNorth,
   location_restaurant_bar_01_29 = SpriteDimensions.HalfNorth,
   location_restaurant_bar_01_30 = SpriteDimensions.HalfNorth,
   location_restaurant_bar_01_31 = SpriteDimensions.HalfNorth,
   location_restaurant_bar_01_64 = SpriteDimensions.HalfNorth,
   location_restaurant_bar_01_65 = SpriteDimensions.HalfNorth,
   location_restaurant_bar_01_66 = SpriteDimensions.HalfNorth,

   furniture_shelving_01_2= SpriteDimensions.HalfWest,
   furniture_shelving_01_10= SpriteDimensions.HalfWest,
   furniture_shelving_01_20= SpriteDimensions.HalfWest,
   furniture_shelving_01_21= SpriteDimensions.HalfWest,
   furniture_shelving_01_22= SpriteDimensions.HalfWest,
   furniture_shelving_01_23= SpriteDimensions.HalfWest,
   furniture_shelving_01_29= SpriteDimensions.HalfWest,
   furniture_shelving_01_32= SpriteDimensions.HalfWest,
   furniture_shelving_01_34= SpriteDimensions.HalfWest,
   furniture_shelving_01_36= SpriteDimensions.HalfWest,
   furniture_shelving_01_41= SpriteDimensions.HalfWest,
   furniture_shelving_01_45= SpriteDimensions.HalfWest,
   furniture_storage_02_9= SpriteDimensions.HalfWest,
   location_restaurant_generic_01_5= SpriteDimensions.HalfWest,
   location_restaurant_generic_01_6= SpriteDimensions.HalfWest,
   location_restaurant_generic_01_13= SpriteDimensions.HalfWest,
   location_restaurant_generic_01_14= SpriteDimensions.HalfWest,
   location_shop_generic_01_3= SpriteDimensions.HalfWest,
   location_shop_generic_01_31= SpriteDimensions.HalfWest,
   location_shop_generic_01_32= SpriteDimensions.HalfWest,
   location_shop_generic_01_33= SpriteDimensions.HalfWest,
   location_shop_generic_01_63= SpriteDimensions.HalfWest,
   location_shop_generic_01_67= SpriteDimensions.HalfWest,
   location_shop_generic_01_68= SpriteDimensions.HalfWest,
   location_shop_generic_01_69= SpriteDimensions.HalfWest,
   location_shop_generic_01_74= SpriteDimensions.HalfWest,
   location_shop_generic_01_75= SpriteDimensions.HalfWest,
   location_shop_generic_01_83= SpriteDimensions.HalfWest,
   location_shop_generic_01_84= SpriteDimensions.HalfWest,
   location_shop_generic_01_85= SpriteDimensions.HalfWest,
   location_shop_generic_01_87= SpriteDimensions.HalfWest,
   location_shop_generic_01_93= SpriteDimensions.HalfWest,

   recreational_01_12= SpriteDimensions.HalfWest,
   recreational_01_13= SpriteDimensions.HalfWest,
   location_restaurant_bar_01_10 = SpriteDimensions.HalfWest,
   location_restaurant_bar_01_11 = SpriteDimensions.HalfWest,
   location_restaurant_bar_01_72 = SpriteDimensions.HalfWest,
   location_restaurant_bar_01_73 = SpriteDimensions.HalfWest,
   location_restaurant_bar_01_74 = SpriteDimensions.HalfWest,
   location_restaurant_bar_01_37 = SpriteDimensions.HalfWest,
   location_restaurant_bar_01_38 = SpriteDimensions.HalfWest,
   location_restaurant_bar_01_39 = SpriteDimensions.HalfWest,

   furniture_shelving_01_3= SpriteDimensions.HalfEast,
   furniture_shelving_01_30= SpriteDimensions.HalfEast,
   furniture_shelving_01_52= SpriteDimensions.HalfEast,
   furniture_shelving_01_53= SpriteDimensions.HalfEast,
   furniture_shelving_01_54= SpriteDimensions.HalfEast,
   furniture_shelving_01_55= SpriteDimensions.HalfEast,
   furniture_shelving_01_42= SpriteDimensions.HalfEast,
   furniture_shelving_01_46= SpriteDimensions.HalfEast,
   furniture_storage_02_11= SpriteDimensions.HalfEast,
   location_restaurant_generic_01_4= SpriteDimensions.HalfEast,
   location_restaurant_generic_01_7= SpriteDimensions.HalfEast,
   location_restaurant_generic_01_12= SpriteDimensions.HalfEast,
   location_restaurant_generic_01_15= SpriteDimensions.HalfEast,
   location_shop_generic_01_28= SpriteDimensions.HalfEast,
   location_shop_generic_01_78= SpriteDimensions.HalfEast,
   location_shop_generic_01_79= SpriteDimensions.HalfEast,
   location_shop_generic_01_94= SpriteDimensions.HalfEast,
   location_trailer_02_4= SpriteDimensions.HalfEast,
   location_trailer_02_5= SpriteDimensions.HalfEast,
   location_restaurant_bar_01_14 = SpriteDimensions.HalfEast,
   location_restaurant_bar_01_15 = SpriteDimensions.HalfEast,


   
   furniture_shelving_01_31= SpriteDimensions.HalfSouth,
   furniture_shelving_01_48= SpriteDimensions.HalfSouth,
   furniture_shelving_01_49= SpriteDimensions.HalfSouth,
   furniture_shelving_01_50= SpriteDimensions.HalfSouth,
   furniture_shelving_01_51= SpriteDimensions.HalfSouth,
   furniture_shelving_01_43= SpriteDimensions.HalfSouth,
   furniture_shelving_01_47= SpriteDimensions.HalfSouth,
   furniture_storage_02_10= SpriteDimensions.HalfSouth,
   location_restaurant_generic_01_1= SpriteDimensions.HalfSouth,
   location_restaurant_generic_01_3= SpriteDimensions.HalfSouth,
   location_restaurant_generic_01_9= SpriteDimensions.HalfSouth,
   location_restaurant_generic_01_11= SpriteDimensions.HalfSouth,
   location_shop_generic_01_29= SpriteDimensions.HalfSouth,
   location_shop_generic_01_76= SpriteDimensions.HalfSouth,
   location_shop_generic_01_77= SpriteDimensions.HalfSouth,
   location_shop_generic_01_95= SpriteDimensions.HalfSouth,
   location_trailer_02_6= SpriteDimensions.HalfSouth,
   location_trailer_02_7= SpriteDimensions.HalfSouth,
   location_restaurant_bar_01_12 = SpriteDimensions.HalfSouth,
   location_restaurant_bar_01_13 = SpriteDimensions.HalfSouth,



   furniture_tables_high_01_4= SpriteDimensions.MiddleLongX,
   furniture_tables_high_01_13= SpriteDimensions.MiddleLongX,
   furniture_tables_high_01_21= SpriteDimensions.MiddleLongX,
   furniture_tables_high_01_5= SpriteDimensions.MiddleLongY,
   furniture_tables_high_01_14= SpriteDimensions.MiddleLongY,
   furniture_tables_high_01_22= SpriteDimensions.MiddleLongY,

   
   location_shop_generic_01_56= SpriteDimensions.MiddleLongY,
   location_shop_generic_01_57= SpriteDimensions.MiddleLongY,
   location_shop_generic_01_58= SpriteDimensions.MiddleLongY,
   location_shop_generic_01_59= SpriteDimensions.MiddleLongX,
   location_shop_generic_01_60= SpriteDimensions.MiddleLongX,
   location_shop_generic_01_61= SpriteDimensions.MiddleLongX,
   
   location_trailer_02_0= SpriteDimensions.MiddleLongY,
   location_trailer_02_1= SpriteDimensions.MiddleLongY,
   location_trailer_02_2= SpriteDimensions.MiddleLongX,
   location_trailer_02_3= SpriteDimensions.MiddleLongX,

   
   furniture_seating_outdoor_01_0 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_1 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_4 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_5 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_8 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_9 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_12 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_13 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_20 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_21 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_32 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_33 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_2 = SpriteDimensions.MiddleLongX,
   furniture_seating_outdoor_01_3 = SpriteDimensions.MiddleLongX,
   furniture_seating_outdoor_01_6 = SpriteDimensions.MiddleLongX,
   furniture_seating_outdoor_01_7 = SpriteDimensions.MiddleLongX,
   furniture_seating_outdoor_01_10 = SpriteDimensions.MiddleLongX,
   furniture_seating_outdoor_01_11 = SpriteDimensions.MiddleLongX,
   furniture_seating_outdoor_01_14 = SpriteDimensions.MiddleLongX,
   furniture_seating_outdoor_01_15 = SpriteDimensions.MiddleLongX,
   furniture_seating_outdoor_01_22 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_23 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_34 = SpriteDimensions.MiddleLongY,
   furniture_seating_outdoor_01_35 = SpriteDimensions.MiddleLongY,
   
}