-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["appliances_refrigeration_erika_01_16"] = {{ name = "other", tiles = {"food_01_90", "food_01_94"} }, { name = "other", tiles = {"food_02_90", "food_02_94"} }}
overlayMap["appliances_refrigeration_erika_01_17"] = {{ name = "other", tiles = {"food_01_91", "food_01_95"} }, { name = "other", tiles = {"food_02_91", "food_02_95"} }}
overlayMap["appliances_refrigeration_erika_01_18"] = {{ name = "other", tiles = {"food_01_88", "food_01_92"} }, { name = "other", tiles = {"food_02_88", "food_02_92"} }}
overlayMap["appliances_refrigeration_erika_01_19"] = {{ name = "other", tiles = {"food_01_89", "food_01_93"} }, { name = "other", tiles = {"food_02_89", "food_02_93"} }}
overlayMap["furniture_shelving_erika_01_0"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["furniture_shelving_erika_01_1"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["furniture_shelving_erika_01_4"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["furniture_shelving_erika_01_5"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["furniture_shelving_erika_01_8"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["furniture_shelving_erika_01_9"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["furniture_shelving_erika_01_12"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["furniture_shelving_erika_01_13"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["furniture_shelving_erika_01_16"] = {{ name = "other", tiles = {"books&misc_01_32", "books&misc_01_40"} }, { name = "other", tiles = {"books&misc_02_32", "books&misc_02_40"} }}
overlayMap["furniture_shelving_erika_01_17"] = {{ name = "other", tiles = {"books&misc_01_33", "books&misc_01_41"} }, { name = "other", tiles = {"books&misc_02_33", "books&misc_02_41"} }}
overlayMap["furniture_shelving_erika_01_18"] = {{ name = "other", tiles = {"books&misc_01_34", "books&misc_01_42"} }, { name = "other", tiles = {"books&misc_02_34", "books&misc_02_42"} }}
overlayMap["furniture_shelving_erika_01_19"] = {{ name = "other", tiles = {"books&misc_01_35", "books&misc_01_43"} }, { name = "other", tiles = {"books&misc_02_35", "books&misc_02_43"} }}
overlayMap["furniture_shelving_erika_01_20"] = {{ name = "other", tiles = {"books&misc_01_36", "books&misc_01_44"} }, { name = "other", tiles = {"books&misc_02_36", "books&misc_02_44"} }}
overlayMap["furniture_shelving_erika_01_21"] = {{ name = "other", tiles = {"books&misc_01_37", "books&misc_01_45"} }, { name = "other", tiles = {"books&misc_02_37", "books&misc_02_45"} }}
overlayMap["furniture_shelving_erika_01_22"] = {{ name = "other", tiles = {"books&misc_01_38", "books&misc_01_46"} }, { name = "other", tiles = {"books&misc_02_38", "books&misc_02_46"} }}
overlayMap["furniture_shelving_erika_01_23"] = {{ name = "other", tiles = {"books&misc_01_39", "books&misc_01_47"} }, { name = "other", tiles = {"books&misc_02_39", "books&misc_02_47"} }}
overlayMap["furniture_shelving_erika_01_32"] = {{ name = "other", tiles = {"books&misc_01_32", "books&misc_01_40"} }, { name = "other", tiles = {"books&misc_02_32", "books&misc_02_40"} }}
overlayMap["furniture_shelving_erika_01_33"] = {{ name = "other", tiles = {"books&misc_01_33", "books&misc_01_41"} }, { name = "other", tiles = {"books&misc_02_33", "books&misc_02_41"} }}
overlayMap["furniture_shelving_erika_01_34"] = {{ name = "other", tiles = {"books&misc_01_34", "books&misc_01_42"} }, { name = "other", tiles = {"books&misc_02_34", "books&misc_02_42"} }}
overlayMap["furniture_shelving_erika_01_35"] = {{ name = "other", tiles = {"books&misc_01_35", "books&misc_01_43"} }, { name = "other", tiles = {"books&misc_02_35", "books&misc_02_43"} }}
overlayMap["furniture_shelving_erika_01_36"] = {{ name = "other", tiles = {"books&misc_01_36", "books&misc_01_44"} }, { name = "other", tiles = {"books&misc_02_36", "books&misc_02_44"} }}
overlayMap["furniture_shelving_erika_01_37"] = {{ name = "other", tiles = {"books&misc_01_37", "books&misc_01_45"} }, { name = "other", tiles = {"books&misc_02_37", "books&misc_02_45"} }}
overlayMap["furniture_shelving_erika_01_38"] = {{ name = "other", tiles = {"books&misc_01_38", "books&misc_01_46"} }, { name = "other", tiles = {"books&misc_02_38", "books&misc_02_46"} }}
overlayMap["furniture_shelving_erika_01_39"] = {{ name = "other", tiles = {"books&misc_01_39", "books&misc_01_47"} }, { name = "other", tiles = {"books&misc_02_39", "books&misc_02_47"} }}
overlayMap["furniture_shelving_erika_01_48"] = {{ name = "other", tiles = {"books&misc_01_32", "books&misc_01_40"} }, { name = "other", tiles = {"books&misc_02_32", "books&misc_02_40"} }}
overlayMap["furniture_shelving_erika_01_49"] = {{ name = "other", tiles = {"books&misc_01_33", "books&misc_01_41"} }, { name = "other", tiles = {"books&misc_02_33", "books&misc_02_41"} }}
overlayMap["furniture_shelving_erika_01_50"] = {{ name = "other", tiles = {"books&misc_01_34", "books&misc_01_42"} }, { name = "other", tiles = {"books&misc_02_34", "books&misc_02_42"} }}
overlayMap["furniture_shelving_erika_01_51"] = {{ name = "other", tiles = {"books&misc_01_35", "books&misc_01_43"} }, { name = "other", tiles = {"books&misc_02_35", "books&misc_02_43"} }}
overlayMap["furniture_shelving_erika_01_52"] = {{ name = "other", tiles = {"books&misc_01_36", "books&misc_01_44"} }, { name = "other", tiles = {"books&misc_02_36", "books&misc_02_44"} }}
overlayMap["furniture_shelving_erika_01_53"] = {{ name = "other", tiles = {"books&misc_01_37", "books&misc_01_45"} }, { name = "other", tiles = {"books&misc_02_37", "books&misc_02_45"} }}
overlayMap["furniture_shelving_erika_01_54"] = {{ name = "other", tiles = {"books&misc_01_38", "books&misc_01_46"} }, { name = "other", tiles = {"books&misc_02_38", "books&misc_02_46"} }}
overlayMap["furniture_shelving_erika_01_55"] = {{ name = "other", tiles = {"books&misc_01_39", "books&misc_01_47"} }, { name = "other", tiles = {"books&misc_02_39", "books&misc_02_47"} }}
overlayMap["furniture_shelving_erika_01_64"] = {{ name = "other", tiles = {"books&misc_01_32", "books&misc_01_40"} }, { name = "other", tiles = {"books&misc_02_32", "books&misc_02_40"} }}
overlayMap["furniture_shelving_erika_01_65"] = {{ name = "other", tiles = {"books&misc_01_33", "books&misc_01_41"} }, { name = "other", tiles = {"books&misc_02_33", "books&misc_02_41"} }}
overlayMap["furniture_shelving_erika_01_66"] = {{ name = "other", tiles = {"books&misc_01_34", "books&misc_01_42"} }, { name = "other", tiles = {"books&misc_02_34", "books&misc_02_42"} }}
overlayMap["furniture_shelving_erika_01_67"] = {{ name = "other", tiles = {"books&misc_01_35", "books&misc_01_43"} }, { name = "other", tiles = {"books&misc_02_35", "books&misc_02_43"} }}
overlayMap["furniture_shelving_erika_01_68"] = {{ name = "other", tiles = {"books&misc_01_36", "books&misc_01_44"} }, { name = "other", tiles = {"books&misc_02_36", "books&misc_02_44"} }}
overlayMap["furniture_shelving_erika_01_69"] = {{ name = "other", tiles = {"books&misc_01_37", "books&misc_01_45"} }, { name = "other", tiles = {"books&misc_02_37", "books&misc_02_45"} }}
overlayMap["furniture_shelving_erika_01_70"] = {{ name = "other", tiles = {"books&misc_01_38", "books&misc_01_46"} }, { name = "other", tiles = {"books&misc_02_38", "books&misc_02_46"} }}
overlayMap["furniture_shelving_erika_01_71"] = {{ name = "other", tiles = {"books&misc_01_39", "books&misc_01_47"} }, { name = "other", tiles = {"books&misc_02_39", "books&misc_02_47"} }}
overlayMap["furniture_shelving_erika_01_80"] = {{ name = "other", tiles = {"books&misc_01_56", "books&misc_01_58"} }, { name = "other", tiles = {"books&misc_02_56", "books&misc_02_58"} }}
overlayMap["furniture_shelving_erika_01_81"] = {{ name = "other", tiles = {"books&misc_01_57", "books&misc_01_59"} }, { name = "other", tiles = {"books&misc_02_57", "books&misc_02_59"} }}
overlayMap["furniture_shelving_erika_01_84"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_32", "overlay_furniture_erika_01_36"} }, { name = "other", tiles = {"overlay_furniture_erika_01_40", "overlay_furniture_erika_01_44"} }}
overlayMap["furniture_shelving_erika_01_85"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_33", "overlay_furniture_erika_01_37"} }, { name = "other", tiles = {"overlay_furniture_erika_01_41", "overlay_furniture_erika_01_45"} }}
overlayMap["furniture_shelving_erika_01_86"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_34", "overlay_furniture_erika_01_38"} }, { name = "other", tiles = {"overlay_furniture_erika_01_42", "overlay_furniture_erika_01_46"} }}
overlayMap["furniture_shelving_erika_01_87"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_35", "overlay_furniture_erika_01_39"} }, { name = "other", tiles = {"overlay_furniture_erika_01_43", "overlay_furniture_erika_01_47"} }}
overlayMap["furniture_shelving_erika_01_88"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_48", "overlay_furniture_erika_01_49"} }, { name = "other", tiles = {"overlay_furniture_erika_01_50", "overlay_furniture_erika_01_51"} }}
overlayMap["furniture_shelving_erika_01_89"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_56", "overlay_furniture_erika_01_58"} }, { name = "other", tiles = {"overlay_furniture_erika_01_60", "overlay_furniture_erika_01_62"} }}
overlayMap["furniture_shelving_erika_01_90"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_57", "overlay_furniture_erika_01_59"} }, { name = "other", tiles = {"overlay_furniture_erika_01_61", "overlay_furniture_erika_01_63"} }}
overlayMap["furniture_shelving_erika_01_91"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_64", "overlay_furniture_erika_01_66"} }, { name = "other", tiles = {"overlay_furniture_erika_01_68", "overlay_furniture_erika_01_70"} }}
overlayMap["furniture_shelving_erika_01_92"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_65", "overlay_furniture_erika_01_67"} }, { name = "other", tiles = {"overlay_furniture_erika_01_69", "overlay_furniture_erika_01_71"} }}
overlayMap["furniture_shelving_erika_01_96"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_52", "overlay_furniture_erika_01_53"} }, { name = "other", tiles = {"overlay_furniture_erika_01_54", "overlay_furniture_erika_01_55"} }}
overlayMap["furniture_shelving_erika_01_97"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_72", "overlay_furniture_erika_01_74"} }, { name = "other", tiles = {"overlay_furniture_erika_01_76", "overlay_furniture_erika_01_78"} }}
overlayMap["furniture_shelving_erika_01_98"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_73", "overlay_furniture_erika_01_75"} }, { name = "other", tiles = {"overlay_furniture_erika_01_77", "overlay_furniture_erika_01_79"} }}
overlayMap["furniture_shelving_erika_01_99"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_80", "overlay_furniture_erika_01_82"} }, { name = "other", tiles = {"overlay_furniture_erika_01_84", "overlay_furniture_erika_01_86"} }}
overlayMap["furniture_shelving_erika_01_100"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_81", "overlay_furniture_erika_01_83"} }, { name = "other", tiles = {"overlay_furniture_erika_01_85", "overlay_furniture_erika_01_87"} }}
overlayMap["furniture_shelving_erika_01_104"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_88", "overlay_furniture_erika_01_90"} }, { name = "other", tiles = {"overlay_furniture_erika_01_92", "overlay_furniture_erika_01_94"} }}
overlayMap["furniture_shelving_erika_01_105"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_89", "overlay_furniture_erika_01_91"} }, { name = "other", tiles = {"overlay_furniture_erika_01_93", "overlay_furniture_erika_01_95"} }}
overlayMap["furniture_shelving_erika_01_108"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_88", "overlay_furniture_erika_01_90"} }, { name = "other", tiles = {"overlay_furniture_erika_01_92", "overlay_furniture_erika_01_94"} }}
overlayMap["furniture_shelving_erika_01_109"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_89", "overlay_furniture_erika_01_91"} }, { name = "other", tiles = {"overlay_furniture_erika_01_93", "overlay_furniture_erika_01_95"} }}
overlayMap["furniture_shelving_erika_01_112"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_88", "overlay_furniture_erika_01_90"} }, { name = "other", tiles = {"overlay_furniture_erika_01_92", "overlay_furniture_erika_01_94"} }}
overlayMap["furniture_shelving_erika_01_113"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_89", "overlay_furniture_erika_01_91"} }, { name = "other", tiles = {"overlay_furniture_erika_01_93", "overlay_furniture_erika_01_95"} }}
overlayMap["furniture_shelving_erika_01_116"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_88", "overlay_furniture_erika_01_90"} }, { name = "other", tiles = {"overlay_furniture_erika_01_92", "overlay_furniture_erika_01_94"} }}
overlayMap["furniture_shelving_erika_01_117"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_89", "overlay_furniture_erika_01_91"} }, { name = "other", tiles = {"overlay_furniture_erika_01_93", "overlay_furniture_erika_01_95"} }}
overlayMap["furniture_shelving_erika_01_120"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_88", "overlay_furniture_erika_01_90"} }, { name = "other", tiles = {"overlay_furniture_erika_01_92", "overlay_furniture_erika_01_94"} }}
overlayMap["furniture_shelving_erika_01_121"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_89", "overlay_furniture_erika_01_91"} }, { name = "other", tiles = {"overlay_furniture_erika_01_93", "overlay_furniture_erika_01_95"} }}
overlayMap["furniture_shelving_erika_01_124"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_88", "overlay_furniture_erika_01_90"} }, { name = "other", tiles = {"overlay_furniture_erika_01_92", "overlay_furniture_erika_01_94"} }}
overlayMap["furniture_shelving_erika_01_125"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_89", "overlay_furniture_erika_01_91"} }, { name = "other", tiles = {"overlay_furniture_erika_01_93", "overlay_furniture_erika_01_95"} }}
overlayMap["furniture_storage_erika_01_16"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_16", "overlay_furniture_erika_01_18"} }}
overlayMap["furniture_storage_erika_01_17"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_17", "overlay_furniture_erika_01_19"} }}
overlayMap["furniture_storage_erika_01_18"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_16", "overlay_furniture_erika_01_18"} }}
overlayMap["furniture_storage_erika_01_19"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_17", "overlay_furniture_erika_01_19"} }}
overlayMap["furniture_storage_erika_01_20"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_16", "overlay_furniture_erika_01_18"} }}
overlayMap["furniture_storage_erika_01_21"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_17", "overlay_furniture_erika_01_19"} }}
overlayMap["furniture_storage_erika_01_22"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_16", "overlay_furniture_erika_01_18"} }}
overlayMap["furniture_storage_erika_01_23"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_17", "overlay_furniture_erika_01_19"} }}
overlayMap["furniture_storage_erika_01_24"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_20", "overlay_furniture_erika_01_22"} }}
overlayMap["furniture_storage_erika_01_25"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_21", "overlay_furniture_erika_01_23"} }}
overlayMap["furniture_storage_erika_01_26"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_20", "overlay_furniture_erika_01_22"} }}
overlayMap["furniture_storage_erika_01_27"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_21", "overlay_furniture_erika_01_23"} }}
overlayMap["furniture_storage_erika_01_28"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_20", "overlay_furniture_erika_01_22"} }}
overlayMap["furniture_storage_erika_01_29"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_21", "overlay_furniture_erika_01_23"} }}
overlayMap["furniture_storage_erika_01_30"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_20", "overlay_furniture_erika_01_22"} }}
overlayMap["furniture_storage_erika_01_31"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_21", "overlay_furniture_erika_01_23"} }}
overlayMap["furniture_storage_erika_03_32"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_24", "overlay_furniture_erika_01_24"} }}
overlayMap["furniture_storage_erika_03_33"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_25", "overlay_furniture_erika_01_25"} }}
overlayMap["furniture_storage_erika_03_34"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_26", "overlay_furniture_erika_01_26"} }}
overlayMap["furniture_storage_erika_03_35"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_27", "overlay_furniture_erika_01_27"} }}
overlayMap["furniture_storage_erika_03_36"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_28", "overlay_furniture_erika_01_28"} }}
overlayMap["furniture_storage_erika_03_37"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_29", "overlay_furniture_erika_01_29"} }}
overlayMap["furniture_storage_erika_03_38"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_30", "overlay_furniture_erika_01_30"} }}
overlayMap["furniture_storage_erika_03_39"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_31", "overlay_furniture_erika_01_31"} }}
overlayMap["furniture_tables_low_01_12"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_0", "overlay_furniture_erika_01_1"} }, { name = "other", tiles = {"overlay_furniture_erika_01_2", "overlay_furniture_erika_01_3"} }}
overlayMap["furniture_tables_low_01_13"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_4", "overlay_furniture_erika_01_5"} }, { name = "other", tiles = {"overlay_furniture_erika_01_6", "overlay_furniture_erika_01_7"} }}
overlayMap["furniture_tables_low_erika_01_0"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_0", "overlay_furniture_erika_01_1"} }, { name = "other", tiles = {"overlay_furniture_erika_01_2", "overlay_furniture_erika_01_3"} }}
overlayMap["furniture_tables_low_erika_01_1"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_4", "overlay_furniture_erika_01_5"} }, { name = "other", tiles = {"overlay_furniture_erika_01_6", "overlay_furniture_erika_01_7"} }}
overlayMap["furniture_tables_low_erika_01_2"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_0", "overlay_furniture_erika_01_1"} }, { name = "other", tiles = {"overlay_furniture_erika_01_2", "overlay_furniture_erika_01_3"} }}
overlayMap["furniture_tables_low_erika_01_3"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_4", "overlay_furniture_erika_01_5"} }, { name = "other", tiles = {"overlay_furniture_erika_01_6", "overlay_furniture_erika_01_7"} }}
overlayMap["furniture_tables_low_erika_01_4"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_0", "overlay_furniture_erika_01_1"} }, { name = "other", tiles = {"overlay_furniture_erika_01_2", "overlay_furniture_erika_01_3"} }}
overlayMap["furniture_tables_low_erika_01_5"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_4", "overlay_furniture_erika_01_5"} }, { name = "other", tiles = {"overlay_furniture_erika_01_6", "overlay_furniture_erika_01_7"} }}
overlayMap["furniture_tables_low_erika_01_6"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_0", "overlay_furniture_erika_01_1"} }, { name = "other", tiles = {"overlay_furniture_erika_01_2", "overlay_furniture_erika_01_3"} }}
overlayMap["furniture_tables_low_erika_01_7"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_4", "overlay_furniture_erika_01_5"} }, { name = "other", tiles = {"overlay_furniture_erika_01_6", "overlay_furniture_erika_01_7"} }}
overlayMap["location_shop_storage_erika_01_0"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_8", "overlay_furniture_erika_01_9"} }, { name = "other", tiles = {"overlay_furniture_erika_01_10", "overlay_furniture_erika_01_11"} }}
overlayMap["location_shop_storage_erika_01_1"] = {{ name = "other", tiles = {"overlay_furniture_erika_01_10", "overlay_furniture_erika_01_11"} }, { name = "other", tiles = {"overlay_furniture_erika_01_8", "overlay_furniture_erika_01_9"} }}
overlayMap["trashcontainers_erika_01_56"] = {{ name = "other", tiles = {"trash&junk_01_0", "trash&junk_01_1"} }, { name = "other", tiles = {"trash&junk_01_8", "trash&junk_01_9"} }}
overlayMap["trashcontainers_erika_01_57"] = {{ name = "other", tiles = {"trash&junk_01_0", "trash&junk_01_1"} }, { name = "other", tiles = {"trash&junk_01_8", "trash&junk_01_9"} }}
overlayMap["trashcontainers_erika_01_58"] = {{ name = "other", tiles = {"trash&junk_01_0", "trash&junk_01_1"} }, { name = "other", tiles = {"trash&junk_01_8", "trash&junk_01_9"} }}
overlayMap["trashcontainers_erika_01_59"] = {{ name = "other", tiles = {"trash&junk_01_0", "trash&junk_01_1"} }, { name = "other", tiles = {"trash&junk_01_8", "trash&junk_01_9"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
