Siding= {};

Siding["doorframe"] = {};
Siding["doorframe"]["PaintBlack"] = "walls_exterior_house_03_10";
Siding["doorframe"]["PaintBlackNorth"] = "walls_exterior_house_03_11";
Siding["doorframe"]["PaintBlue"] = "walls_exterior_house_03_14";
Siding["doorframe"]["PaintBlueNorth"] = "walls_exterior_house_03_15";
Siding["doorframe"]["PaintBrown"] = "walls_exterior_house_04_94";
Siding["doorframe"]["PaintBrownNorth"] = "walls_exterior_house_04_95";
Siding["doorframe"]["PaintCyan"] = "walls_exterior_house_02_30";
Siding["doorframe"]["PaintCyanNorth"] = "walls_exterior_house_02_31";
Siding["doorframe"]["PaintGreen"] = "walls_exterior_house_02_90";
Siding["doorframe"]["PaintGreenNorth"] = "walls_exterior_house_02_91";
Siding["doorframe"]["PaintGrey"] = "walls_exterior_house_01_58";
Siding["doorframe"]["PaintGreyNorth"] = "walls_exterior_house_01_59";
Siding["doorframe"]["PaintLightBlue"] = "walls_exterior_house_03_26";
Siding["doorframe"]["PaintLightBlueNorth"] = "walls_exterior_house_03_27";
Siding["doorframe"]["PaintLightBrown"] = "walls_exterior_house_03_30";
Siding["doorframe"]["PaintLightBrownNorth"] = "walls_exterior_house_03_31";
Siding["doorframe"]["PaintOrange"] = "walls_exterior_house_03_42";
Siding["doorframe"]["PaintOrangeNorth"] = "walls_exterior_house_03_43";
Siding["doorframe"]["PaintPink"] = "walls_exterior_house_02_78";
Siding["doorframe"]["PaintPinkNorth"] = "walls_exterior_house_02_79";
Siding["doorframe"]["PaintPurple"] = "walls_exterior_house_03_46";
Siding["doorframe"]["PaintPurpleNorth"] = "walls_exterior_house_03_47";
Siding["doorframe"]["PaintRed"] = "walls_exterior_house_03_58";
Siding["doorframe"]["PaintRedNorth"] = "walls_exterior_house_03_59";
Siding["doorframe"]["PaintTurquoise"] = "walls_exterior_house_03_62";
Siding["doorframe"]["PaintTurquoiseNorth"] = "walls_exterior_house_03_63";
Siding["doorframe"]["PaintWhite"] = "walls_exterior_house_01_42";
Siding["doorframe"]["PaintWhiteNorth"] = "walls_exterior_house_01_43";
Siding["doorframe"]["PaintYellow"] = "walls_exterior_house_03_74";
Siding["doorframe"]["PaintYellowNorth"] = "walls_exterior_house_03_75";
Siding["doorframe"]["PaintMagenta"] = "walls_exterior_house_03_78";
Siding["doorframe"]["PaintMagentaNorth"] = "walls_exterior_house_03_79";
Siding["doorframe"]["PaintDustBlue"] = "walls_exterior_house_03_90";
Siding["doorframe"]["PaintDustBlueNorth"] = "walls_exterior_house_03_91";
Siding["doorframe"]["PaintDustGreen"] = "walls_exterior_house_03_94";
Siding["doorframe"]["PaintDustGreenNorth"] = "walls_exterior_house_03_95";
Siding["doorframe"]["PaintCamoGreen"] = "walls_exterior_house_04_10";
Siding["doorframe"]["PaintCamoGreenNorth"] = "walls_exterior_house_04_11";
Siding["doorframe"]["PaintIvory"] = "walls_exterior_house_04_14";
Siding["doorframe"]["PaintIvoryNorth"] = "walls_exterior_house_04_15";
Siding["doorframe"]["PaintMidGreen"] = "walls_exterior_house_04_30";
Siding["doorframe"]["PaintMidGreenNorth"] = "walls_exterior_house_04_31";
Siding["doorframe"]["PaintMidBlue"] = "walls_exterior_house_04_26";
Siding["doorframe"]["PaintMidBlueNorth"] = "walls_exterior_house_04_27";
Siding["doorframe"]["PaintLightOrange"] = "walls_exterior_house_04_42";
Siding["doorframe"]["PaintLightOrangeNorth"] = "walls_exterior_house_04_43";
Siding["doorframe"]["PaintWine"] = "walls_exterior_house_04_46";
Siding["doorframe"]["PaintWineNorth"] = "walls_exterior_house_04_47";
Siding["doorframe"]["PaintLightYellow"] = "walls_exterior_house_04_62";
Siding["doorframe"]["PaintLightYellowNorth"] = "walls_exterior_house_04_63";
Siding["doorframe"]["PaintBeige"] = "walls_exterior_house_02_42";
Siding["doorframe"]["PaintBeigeNorth"] = "walls_exterior_house_02_43";
Siding["doorframe"]["PaintViolet"] = "walls_exterior_house_04_74";
Siding["doorframe"]["PaintVioletNorth"] = "walls_exterior_house_04_75";
Siding["doorframe"]["PaintPeach"] = "walls_exterior_house_04_78";
Siding["doorframe"]["PaintPeachNorth"] = "walls_exterior_house_04_79";
Siding["doorframe"]["PaintDarkGrey"] = "walls_exterior_house_04_90";
Siding["doorframe"]["PaintDarkGreyNorth"] = "walls_exterior_house_04_91";
Siding["doorframe"]["PaintDustOrange"] = "walls_exterior_house_05_10";
Siding["doorframe"]["PaintDustOrangeNorth"] = "walls_exterior_house_05_11";
Siding["doorframe"]["PaintLime"] = "walls_exterior_house_05_14";
Siding["doorframe"]["PaintLimeNorth"] = "walls_exterior_house_05_15";


Siding["pillar"] = {};
Siding["pillar"]["PaintBlack"] = "walls_exterior_house_03_3"; -- ФШ
Siding["pillar"]["PaintBlue"] = "walls_exterior_house_03_7"; -- ФШ
Siding["pillar"]["PaintBrown"] = "walls_exterior_house_04_87"; --
Siding["pillar"]["PaintCyan"] = "walls_exterior_house_02_23"; -- Игра
Siding["pillar"]["PaintGreen"] = "walls_exterior_house_02_83"; -- Игра
Siding["pillar"]["PaintGrey"] = "walls_exterior_house_01_51"; -- Игра
Siding["pillar"]["PaintLightBlue"] = "walls_exterior_house_03_19"; -- ФШ
Siding["pillar"]["PaintLightBrown"] = "walls_exterior_house_03_23"; --ФШ
Siding["pillar"]["PaintOrange"] = "walls_exterior_house_03_35"; -- ФШ
Siding["pillar"]["PaintPink"] = "walls_exterior_house_02_71"; --Игра
Siding["pillar"]["PaintPurple"] = "walls_exterior_house_03_39"; --ФШ
Siding["pillar"]["PaintRed"] = "walls_exterior_house_03_51"; -- ФШ
Siding["pillar"]["PaintTurquoise"] = "walls_exterior_house_03_55"; --ФШ
Siding["pillar"]["PaintWhite"] = "walls_exterior_house_01_35"; -- Игра
Siding["pillar"]["PaintYellow"] = "walls_exterior_house_03_67";
Siding["pillar"]["PaintMagenta"] = "walls_exterior_house_03_71"; --ФШ
Siding["pillar"]["PaintDustBlue"] = "walls_exterior_house_03_83"; --ФШ
Siding["pillar"]["PaintDustGreen"] = "walls_exterior_house_03_87"; -- ФШ
Siding["pillar"]["PaintCamoGreen"] = "walls_exterior_house_04_3"; -- ФШ
Siding["pillar"]["PaintIvory"] = "walls_exterior_house_04_7"; --ФШ
Siding["pillar"]["PaintMidBlue"] = "walls_exterior_house_04_19"; -- ФШ
Siding["pillar"]["PaintMidGreen"] = "walls_exterior_house_04_23"; -- ФШ
Siding["pillar"]["PaintLightOrange"] = "walls_exterior_house_04_35";  --ФШ
Siding["pillar"]["PaintWine"] = "walls_exterior_house_04_39"; --ФШ
Siding["pillar"]["PaintLightYellow"] = "walls_exterior_house_04_55"; --ФШ
Siding["pillar"]["PaintBeige"] = "walls_exterior_house_02_35";--Игра
Siding["pillar"]["PaintViolet"] = "walls_exterior_house_04_67";
Siding["pillar"]["PaintPeach"] = "walls_exterior_house_04_71";
Siding["pillar"]["PaintDarkGrey"] = "walls_exterior_house_04_83";
Siding["pillar"]["PaintDustOrange"] = "walls_exterior_house_05_3";
Siding["pillar"]["PaintLime"] = "walls_exterior_house_05_7";

Siding["wall"] = {};
Siding["wall"]["PaintBlack"] = "walls_exterior_house_03_0";
Siding["wall"]["PaintBlackCorner"] = "walls_exterior_house_03_2";
Siding["wall"]["PaintBlackNorth"] = "walls_exterior_house_03_1";
Siding["wall"]["PaintBlue"] = "walls_exterior_house_03_4";
Siding["wall"]["PaintBlueCorner"] = "walls_exterior_house_03_6";
Siding["wall"]["PaintBlueNorth"] = "walls_exterior_house_03_5";
Siding["wall"]["PaintBrown"] = "walls_exterior_house_04_84";
Siding["wall"]["PaintBrownCorner"] = "walls_exterior_house_04_86";
Siding["wall"]["PaintBrownNorth"] = "walls_exterior_house_04_85";
Siding["wall"]["PaintCyan"] = "walls_exterior_house_02_20";
Siding["wall"]["PaintCyanCorner"] = "walls_exterior_house_02_22";
Siding["wall"]["PaintCyanNorth"] = "walls_exterior_house_02_21";
Siding["wall"]["PaintGreen"] = "walls_exterior_house_02_80";
Siding["wall"]["PaintGreenCorner"] = "walls_exterior_house_02_82";
Siding["wall"]["PaintGreenNorth"] = "walls_exterior_house_02_81";
Siding["wall"]["PaintGrey"] = "walls_exterior_house_01_48";
Siding["wall"]["PaintGreyCorner"] = "walls_exterior_house_01_50";
Siding["wall"]["PaintGreyNorth"] = "walls_exterior_house_01_49";
Siding["wall"]["PaintLightBlue"] = "walls_exterior_house_03_16";
Siding["wall"]["PaintLightBlueCorner"] = "walls_exterior_house_03_18";
Siding["wall"]["PaintLightBlueNorth"] = "walls_exterior_house_03_17";
Siding["wall"]["PaintLightBrown"] = "walls_exterior_house_03_20";
Siding["wall"]["PaintLightBrownCorner"] = "walls_exterior_house_03_22";
Siding["wall"]["PaintLightBrownNorth"] = "walls_exterior_house_03_21";
Siding["wall"]["PaintOrange"] = "walls_exterior_house_03_32";
Siding["wall"]["PaintOrangeCorner"] = "walls_exterior_house_03_34";
Siding["wall"]["PaintOrangeNorth"] = "walls_exterior_house_03_33";
Siding["wall"]["PaintPink"] = "walls_exterior_house_02_68";
Siding["wall"]["PaintPinkCorner"] = "walls_exterior_house_02_70";
Siding["wall"]["PaintPinkNorth"] = "walls_exterior_house_02_69";
Siding["wall"]["PaintPurple"] = "walls_exterior_house_03_36";
Siding["wall"]["PaintPurpleCorner"] = "walls_exterior_house_03_38";
Siding["wall"]["PaintPurpleNorth"] = "walls_exterior_house_03_37";
Siding["wall"]["PaintRed"] = "walls_exterior_house_03_48";
Siding["wall"]["PaintRedCorner"] = "walls_exterior_house_03_50";
Siding["wall"]["PaintRedNorth"] = "walls_exterior_house_03_49";
Siding["wall"]["PaintTurquoise"] = "walls_exterior_house_03_52";
Siding["wall"]["PaintTurquoiseCorner"] = "walls_exterior_house_03_54";
Siding["wall"]["PaintTurquoiseNorth"] = "walls_exterior_house_03_53";
Siding["wall"]["PaintWhite"] = "walls_exterior_house_01_32";
Siding["wall"]["PaintWhiteCorner"] = "walls_exterior_house_01_34";
Siding["wall"]["PaintWhiteNorth"] = "walls_exterior_house_01_33";
Siding["wall"]["PaintYellow"] = "walls_exterior_house_03_64";
Siding["wall"]["PaintYellowCorner"] = "walls_exterior_house_03_66";
Siding["wall"]["PaintYellowNorth"] = "walls_exterior_house_03_65";
Siding["wall"]["PaintMagenta"] = "walls_exterior_house_03_68";
Siding["wall"]["PaintMagentaCorner"] = "walls_exterior_house_03_70";
Siding["wall"]["PaintMagentaNorth"] = "walls_exterior_house_03_69";
Siding["wall"]["PaintDustBlue"] = "walls_exterior_house_03_80";
Siding["wall"]["PaintDustBlueCorner"] = "walls_exterior_house_03_82";
Siding["wall"]["PaintDustBlueNorth"] = "walls_exterior_house_03_81";
Siding["wall"]["PaintDustGreen"] = "walls_exterior_house_03_84";
Siding["wall"]["PaintDustGreenCorner"] = "walls_exterior_house_03_86";
Siding["wall"]["PaintDustGreenNorth"] = "walls_exterior_house_03_85";
Siding["wall"]["PaintCamoGreen"] = "walls_exterior_house_04_0";
Siding["wall"]["PaintCamoGreenCorner"] = "walls_exterior_house_04_2";
Siding["wall"]["PaintCamoGreenNorth"] = "walls_exterior_house_04_1";
Siding["wall"]["PaintIvory"] = "walls_exterior_house_04_4";
Siding["wall"]["PaintIvoryCorner"] = "walls_exterior_house_04_6";
Siding["wall"]["PaintIvoryNorth"] = "walls_exterior_house_04_5";
Siding["wall"]["PaintMidBlue"] = "walls_exterior_house_04_16";
Siding["wall"]["PaintMidBlueCorner"] = "walls_exterior_house_04_18";
Siding["wall"]["PaintMidBlueNorth"] = "walls_exterior_house_04_17";
Siding["wall"]["PaintMidGreen"] = "walls_exterior_house_04_20";
Siding["wall"]["PaintMidGreenCorner"] = "walls_exterior_house_04_22";
Siding["wall"]["PaintMidGreenNorth"] = "walls_exterior_house_04_21";
Siding["wall"]["PaintLightOrange"] = "walls_exterior_house_04_32";
Siding["wall"]["PaintLightOrangeCorner"] = "walls_exterior_house_04_34";
Siding["wall"]["PaintLightOrangeNorth"] = "walls_exterior_house_04_33";
Siding["wall"]["PaintWine"] = "walls_exterior_house_04_36";
Siding["wall"]["PaintWineCorner"] = "walls_exterior_house_04_38";
Siding["wall"]["PaintWineNorth"] = "walls_exterior_house_04_37";
Siding["wall"]["PaintLightYellow"] = "walls_exterior_house_04_52";
Siding["wall"]["PaintLightYellowCorner"] = "walls_exterior_house_04_54";
Siding["wall"]["PaintLightYellowNorth"] = "walls_exterior_house_04_53";
Siding["wall"]["PaintBeige"] = "walls_exterior_house_02_32";
Siding["wall"]["PaintBeigeCorner"] = "walls_exterior_house_02_34";
Siding["wall"]["PaintBeigeNorth"] = "walls_exterior_house_02_33";
Siding["wall"]["PaintViolet"] = "walls_exterior_house_04_64";
Siding["wall"]["PaintVioletCorner"] = "walls_exterior_house_04_66";
Siding["wall"]["PaintVioletNorth"] = "walls_exterior_house_04_65";
Siding["wall"]["PaintPeach"] = "walls_exterior_house_04_68";
Siding["wall"]["PaintPeachCorner"] = "walls_exterior_house_04_70";
Siding["wall"]["PaintPeachNorth"] = "walls_exterior_house_04_69";
Siding["wall"]["PaintDarkGrey"] = "walls_exterior_house_04_80";
Siding["wall"]["PaintDarkGreyCorner"] = "walls_exterior_house_04_82";
Siding["wall"]["PaintDarkGreyNorth"] = "walls_exterior_house_04_81";
Siding["wall"]["PaintDustOrange"] = "walls_exterior_house_05_0";
Siding["wall"]["PaintDustOrangeCorner"] = "walls_exterior_house_05_2";
Siding["wall"]["PaintDustOrangeNorth"] = "walls_exterior_house_05_1";
Siding["wall"]["PaintLime"] = "walls_exterior_house_05_4";
Siding["wall"]["PaintLimeCorner"] = "walls_exterior_house_05_6";
Siding["wall"]["PaintLimeNorth"] = "walls_exterior_house_05_5";

Siding["windowsframe"] = {};
Siding["windowsframe"]["PaintBlack"] = "walls_exterior_house_03_8";
Siding["windowsframe"]["PaintBlackNorth"] = "walls_exterior_house_03_9";
Siding["windowsframe"]["PaintBlue"] = "walls_exterior_house_03_12";
Siding["windowsframe"]["PaintBlueNorth"] = "walls_exterior_house_03_13";
Siding["windowsframe"]["PaintBrown"] = "walls_exterior_house_04_92";
Siding["windowsframe"]["PaintBrownNorth"] = "walls_exterior_house_04_93";
Siding["windowsframe"]["PaintCyan"] = "walls_exterior_house_02_28";
Siding["windowsframe"]["PaintCyanNorth"] = "walls_exterior_house_02_29";
Siding["windowsframe"]["PaintGreen"] = "walls_exterior_house_02_88";
Siding["windowsframe"]["PaintGreenNorth"] = "walls_exterior_house_02_89";
Siding["windowsframe"]["PaintGrey"] = "walls_exterior_house_01_56";
Siding["windowsframe"]["PaintGreyNorth"] = "walls_exterior_house_01_57";
Siding["windowsframe"]["PaintLightBlue"] = "walls_exterior_house_03_24";
Siding["windowsframe"]["PaintLightBlueNorth"] = "walls_exterior_house_03_25";
Siding["windowsframe"]["PaintLightBrown"] = "walls_exterior_house_03_28";
Siding["windowsframe"]["PaintLightBrownNorth"] = "walls_exterior_house_03_29";
Siding["windowsframe"]["PaintOrange"] = "walls_exterior_house_03_40";
Siding["windowsframe"]["PaintOrangeNorth"] = "walls_exterior_house_03_41";
Siding["windowsframe"]["PaintPink"] = "walls_exterior_house_02_76";
Siding["windowsframe"]["PaintPinkNorth"] = "walls_exterior_house_02_77";
Siding["windowsframe"]["PaintPurple"] = "walls_exterior_house_03_44";
Siding["windowsframe"]["PaintPurpleNorth"] = "walls_exterior_house_03_45";
Siding["windowsframe"]["PaintRed"] = "walls_exterior_house_03_56";
Siding["windowsframe"]["PaintRedNorth"] = "walls_exterior_house_03_57";
Siding["windowsframe"]["PaintTurquoise"] = "walls_exterior_house_03_60";
Siding["windowsframe"]["PaintTurquoiseNorth"] = "walls_exterior_house_03_61";
Siding["windowsframe"]["PaintWhite"] = "walls_exterior_house_01_40";
Siding["windowsframe"]["PaintWhiteNorth"] = "walls_exterior_house_01_41";
Siding["windowsframe"]["PaintYellow"] = "walls_exterior_house_03_72";
Siding["windowsframe"]["PaintYellowNorth"] = "walls_exterior_house_03_73";
Siding["windowsframe"]["PaintMagenta"] = "walls_exterior_house_03_76";
Siding["windowsframe"]["PaintMagentaNorth"] = "walls_exterior_house_03_77";
Siding["windowsframe"]["PaintDustBlue"] = "walls_exterior_house_03_88";
Siding["windowsframe"]["PaintDustBlueNorth"] = "walls_exterior_house_03_89";
Siding["windowsframe"]["PaintDustGreen"] = "walls_exterior_house_03_92";
Siding["windowsframe"]["PaintDustGreenNorth"] = "walls_exterior_house_03_93";
Siding["windowsframe"]["PaintCamoGreen"] = "walls_exterior_house_04_8";
Siding["windowsframe"]["PaintCamoGreenNorth"] = "walls_exterior_house_04_9";
Siding["windowsframe"]["PaintIvory"] = "walls_exterior_house_04_12";
Siding["windowsframe"]["PaintIvoryNorth"] = "walls_exterior_house_04_13";
Siding["windowsframe"]["PaintMidBlue"] = "walls_exterior_house_04_24";
Siding["windowsframe"]["PaintMidBlueNorth"] = "walls_exterior_house_04_25";
Siding["windowsframe"]["PaintMidGreen"] = "walls_exterior_house_04_28";
Siding["windowsframe"]["PaintMidGreenNorth"] = "walls_exterior_house_04_29";
Siding["windowsframe"]["PaintLightOrange"] = "walls_exterior_house_04_40";
Siding["windowsframe"]["PaintLightOrangeNorth"] = "walls_exterior_house_04_41";
Siding["windowsframe"]["PaintWine"] = "walls_exterior_house_04_44";
Siding["windowsframe"]["PaintWineNorth"] = "walls_exterior_house_04_45";
Siding["windowsframe"]["PaintLightYellow"] = "walls_exterior_house_04_60";
Siding["windowsframe"]["PaintLightYellowNorth"] = "walls_exterior_house_04_61";
Siding["windowsframe"]["PaintBeige"] = "walls_exterior_house_02_40";
Siding["windowsframe"]["PaintBeigeNorth"] = "walls_exterior_house_02_41";
Siding["windowsframe"]["PaintViolet"] = "walls_exterior_house_04_72";
Siding["windowsframe"]["PaintVioletNorth"] = "walls_exterior_house_04_73";
Siding["windowsframe"]["PaintPeach"] = "walls_exterior_house_04_76";
Siding["windowsframe"]["PaintPeachNorth"] = "walls_exterior_house_04_77";
Siding["windowsframe"]["PaintDarkGrey"] = "walls_exterior_house_04_88";
Siding["windowsframe"]["PaintDarkGreyNorth"] = "walls_exterior_house_04_89";
Siding["windowsframe"]["PaintDustOrange"] = "walls_exterior_house_05_8";
Siding["windowsframe"]["PaintDustOrangeNorth"] = "walls_exterior_house_05_9";
Siding["windowsframe"]["PaintLime"] = "walls_exterior_house_05_12";
Siding["windowsframe"]["PaintLimeNorth"] = "walls_exterior_house_05_13";

