require "Items/ProceduralDistributions.lua"

table.insert(ProceduralDistributions.list.CrateMechanics.items,"TapDie")
table.insert(ProceduralDistributions.list.CrateMechanics.items,5)
table.insert(ProceduralDistributions.list.CrateMechanics.items,"MotorOil")
table.insert(ProceduralDistributions.list.CrateMechanics.items,7)
table.insert(ProceduralDistributions.list.CrateMechanics.items,"OilFilter")
table.insert(ProceduralDistributions.list.CrateMechanics.items,7)
table.insert(ProceduralDistributions.list.CrateMechanics.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.CrateMechanics.items,7)
table.insert(ProceduralDistributions.list.MechanicShelfSuspension.items,"TapDie")
table.insert(ProceduralDistributions.list.MechanicShelfSuspension.items,2)
table.insert(ProceduralDistributions.list.MechanicShelfSuspension.items,"MotorOil")
table.insert(ProceduralDistributions.list.MechanicShelfSuspension.items,2.8)
table.insert(ProceduralDistributions.list.MechanicShelfSuspension.items,"OilFilter")
table.insert(ProceduralDistributions.list.MechanicShelfSuspension.items,2.8)
table.insert(ProceduralDistributions.list.MechanicShelfSuspension.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.MechanicShelfSuspension.items,2.8)
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,"TapDie")
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,2)
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,"ToolFile")
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,3)
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,"MotorOil")
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,2.8)
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,"OilFilter")
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,2.8)
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,2.8)
table.insert(ProceduralDistributions.list.MechanicShelfMufflers.items,"TapDie")
table.insert(ProceduralDistributions.list.MechanicShelfMufflers.items,2)
table.insert(ProceduralDistributions.list.MechanicShelfMufflers.items,"MotorOil")
table.insert(ProceduralDistributions.list.MechanicShelfMufflers.items,2.8)
table.insert(ProceduralDistributions.list.MechanicShelfMufflers.items,"OilFilter")
table.insert(ProceduralDistributions.list.MechanicShelfMufflers.items,2.8)
table.insert(ProceduralDistributions.list.MechanicShelfMufflers.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.MechanicShelfMufflers.items,2.8)
table.insert(ProceduralDistributions.list.CrateRandomJunk.items,"TapDie")
table.insert(ProceduralDistributions.list.CrateRandomJunk.items,5)
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,"ToolFile")
table.insert(ProceduralDistributions.list.MechanicShelfBrakes.items,6)
table.insert(ProceduralDistributions.list.CrateRandomJunk.items,"MotorOil")
table.insert(ProceduralDistributions.list.CrateRandomJunk.items,7)
table.insert(ProceduralDistributions.list.CrateRandomJunk.items,"OilFilter")
table.insert(ProceduralDistributions.list.CrateRandomJunk.items,7)
table.insert(ProceduralDistributions.list.CrateRandomJunk.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.CrateRandomJunk.items,7)
table.insert(ProceduralDistributions.list.GasStorageMechanics.items,"TapDie")
table.insert(ProceduralDistributions.list.GasStorageMechanics.items,5)
table.insert(ProceduralDistributions.list.GasStorageMechanics.items,"ToolFile")
table.insert(ProceduralDistributions.list.GasStorageMechanics.items,6)
table.insert(ProceduralDistributions.list.GasStorageMechanics.items,"MotorOil")
table.insert(ProceduralDistributions.list.GasStorageMechanics.items,7)
table.insert(ProceduralDistributions.list.GasStorageMechanics.items,"OilFilter")
table.insert(ProceduralDistributions.list.GasStorageMechanics.items,7)
table.insert(ProceduralDistributions.list.GasStorageMechanics.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.GasStorageMechanics.items,7)
table.insert(ProceduralDistributions.list.MechanicShelfWheels.items,"TapDie")
table.insert(ProceduralDistributions.list.MechanicShelfWheels.items,2)
table.insert(ProceduralDistributions.list.MechanicShelfWheels.items,"ToolFile")
table.insert(ProceduralDistributions.list.MechanicShelfWheels.items,6)
table.insert(ProceduralDistributions.list.MechanicShelfWheels.items,"MotorOil")
table.insert(ProceduralDistributions.list.MechanicShelfWheels.items,2.8)
table.insert(ProceduralDistributions.list.MechanicShelfWheels.items,"OilFilter")
table.insert(ProceduralDistributions.list.MechanicShelfWheels.items,2.8)
table.insert(ProceduralDistributions.list.MechanicShelfWheels.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.MechanicShelfWheels.items,2.8)
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items,"TapDie")
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items,5)
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items,"ToolFile")
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items,6)
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items,"MotorOil")
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items,7)
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items,"OilFilter")
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items,7)
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items,7)
table.insert(ProceduralDistributions.list.GarageMechanics.items,"TapDie")
table.insert(ProceduralDistributions.list.GarageMechanics.items,0.75)
table.insert(ProceduralDistributions.list.GarageMechanics.items,"ToolFile")
table.insert(ProceduralDistributions.list.GarageMechanics.items,2)
table.insert(ProceduralDistributions.list.GarageMechanics.items,"MotorOil")
table.insert(ProceduralDistributions.list.GarageMechanics.items,1.05)
table.insert(ProceduralDistributions.list.GarageMechanics.items,"OilFilter")
table.insert(ProceduralDistributions.list.GarageMechanics.items,1.05)
table.insert(ProceduralDistributions.list.GarageMechanics.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.GarageMechanics.items,1.05)
table.insert(ProceduralDistributions.list.GigamartTools.items,"TapDie")
table.insert(ProceduralDistributions.list.GigamartTools.items,0.75)
table.insert(ProceduralDistributions.list.GigamartTools.items,"ToolFile")
table.insert(ProceduralDistributions.list.GigamartTools.items,2)
table.insert(ProceduralDistributions.list.GigamartTools.items,"MotorOil")
table.insert(ProceduralDistributions.list.GigamartTools.items,1.05)
table.insert(ProceduralDistributions.list.GigamartTools.items,"OilFilter")
table.insert(ProceduralDistributions.list.GigamartTools.items,1.05)
table.insert(ProceduralDistributions.list.GigamartTools.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.GigamartTools.items,1.05)
table.insert(ProceduralDistributions.list.MechanicSpecial.items,"TapDie")
table.insert(ProceduralDistributions.list.MechanicSpecial.items,0.75)
table.insert(ProceduralDistributions.list.MechanicSpecial.items,"ToolFile")
table.insert(ProceduralDistributions.list.MechanicSpecial.items,2)
table.insert(ProceduralDistributions.list.MechanicSpecial.items,"MotorOil")
table.insert(ProceduralDistributions.list.MechanicSpecial.items,1.05)
table.insert(ProceduralDistributions.list.MechanicSpecial.items,"OilFilter")
table.insert(ProceduralDistributions.list.MechanicSpecial.items,1.05)
table.insert(ProceduralDistributions.list.MechanicSpecial.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.MechanicSpecial.items,1.05)
table.insert(ProceduralDistributions.list.ArmyHangarTools.items,"TapDie")
table.insert(ProceduralDistributions.list.ArmyHangarTools.items,5)
table.insert(ProceduralDistributions.list.ArmyHangarTools.items,"ToolFile")
table.insert(ProceduralDistributions.list.ArmyHangarTools.items,6)
table.insert(ProceduralDistributions.list.CrateTools.items,"TapDie")
table.insert(ProceduralDistributions.list.CrateTools.items,5)
table.insert(ProceduralDistributions.list.CrateTools.items,"ToolFile")
table.insert(ProceduralDistributions.list.CrateTools.items,6)
table.insert(ProceduralDistributions.list.DrugShackTools .items,"TapDie")
table.insert(ProceduralDistributions.list.DrugShackTools .items,5)
table.insert(ProceduralDistributions.list.DrugShackTools.items,"ToolFile")
table.insert(ProceduralDistributions.list.DrugShackTools.items,6)
table.insert(ProceduralDistributions.list.GarageTools.items,"TapDie")
table.insert(ProceduralDistributions.list.GarageTools.items,2)
table.insert(ProceduralDistributions.list.GarageTools.items,"ToolFile")
table.insert(ProceduralDistributions.list.GarageTools.items,6)
table.insert(ProceduralDistributions.list.GarageTools.items,"MotorOil")
table.insert(ProceduralDistributions.list.GarageTools.items,2.8)
table.insert(ProceduralDistributions.list.GarageTools.items,"OilFilter")
table.insert(ProceduralDistributions.list.GarageTools.items,2.8)
table.insert(ProceduralDistributions.list.GarageTools.items,"LargeOilFilter")
table.insert(ProceduralDistributions.list.GarageTools.items,2.8)
table.insert(ProceduralDistributions.list.GeneratorRoom.items,"TapDie")
table.insert(ProceduralDistributions.list.GeneratorRoom.items,5)
table.insert(ProceduralDistributions.list.GeneratorRoom.items,"ToolFile")
table.insert(ProceduralDistributions.list.GeneratorRoom.items,6)
table.insert(ProceduralDistributions.list.MechanicShelfOutfit.items,"TapDie")
table.insert(ProceduralDistributions.list.MechanicShelfOutfit.items,5)
table.insert(ProceduralDistributions.list.MechanicShelfOutfit.items,"ToolFile")
table.insert(ProceduralDistributions.list.MechanicShelfOutfit.items,6)
table.insert(ProceduralDistributions.list.MechanicShelfTools.items,"TapDie")
table.insert(ProceduralDistributions.list.MechanicShelfTools.items,5)
table.insert(ProceduralDistributions.list.MechanicShelfTools.items,"ToolFile")
table.insert(ProceduralDistributions.list.MechanicShelfTools.items,6)
table.insert(ProceduralDistributions.list.MechanicSpecial.items,"TapDie")
table.insert(ProceduralDistributions.list.MechanicSpecial.items,5)
table.insert(ProceduralDistributions.list.MechanicSpecial.items,"ToolFile")
table.insert(ProceduralDistributions.list.MechanicSpecial.items,6)
table.insert(ProceduralDistributions.list.PlumbingSupplies.items,"TapDie")
table.insert(ProceduralDistributions.list.PlumbingSupplies.items,5)
table.insert(ProceduralDistributions.list.PlumbingSupplies.items,"ToolFile")
table.insert(ProceduralDistributions.list.PlumbingSupplies.items,6)
table.insert(ProceduralDistributions.list.ToolStoreTools.items,"TapDie")
table.insert(ProceduralDistributions.list.ToolStoreTools.items,5)
table.insert(ProceduralDistributions.list.ToolStoreTools.items,"ToolFile")
table.insert(ProceduralDistributions.list.ToolStoreTools.items,6)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"SilencerMag")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.5)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"AutoConMag")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.5)
table.insert(ProceduralDistributions.list.CrateMagazines.items,"SilencerMag")
table.insert(ProceduralDistributions.list.CrateMagazines.items,0.5)
table.insert(ProceduralDistributions.list.CrateMagazines.items,"AutoConMag")
table.insert(ProceduralDistributions.list.CrateMagazines.items,0.5)
table.insert(ProceduralDistributions.list.GunStoreMagazineRack.items,"SilencerMag")
table.insert(ProceduralDistributions.list.GunStoreMagazineRack.items,1)
table.insert(ProceduralDistributions.list.GunStoreMagazineRack.items,"AutoConMag")
table.insert(ProceduralDistributions.list.GunStoreMagazineRack.items,1)
table.insert(ProceduralDistributions.list.PlankStashMagazine.items, "SilencerMag")
table.insert(ProceduralDistributions.list.PlankStashMagazine.items, 15)
table.insert(ProceduralDistributions.list.PlankStashMagazine.items, "AutoConMag")
table.insert(ProceduralDistributions.list.PlankStashMagazine.items, 15)
table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "SilencerMag")
table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 0.05)
table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "AutoConMag")
table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 0.05)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items, "SilencerMag")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items, 0.4)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items, "AutoConMag")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items, 0.4)
table.insert(ProceduralDistributions.list.PawnShopGuns.items, "SilencerMag")
table.insert(ProceduralDistributions.list.PawnShopGuns.items, 0.2)
table.insert(ProceduralDistributions.list.PawnShopGuns.items, "AutoConMag")
table.insert(ProceduralDistributions.list.PawnShopGuns.items, 0.2)