require "Definitions/AttachedWeaponDefinitions"

if not SandboxVars.Guns93.Guns93ZedBayonet or not SandboxVars.Guns93.Guns93BayoDistro then
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.M5Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.M5Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.M4Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.M1905Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.M1917Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetBack"].weapons,"Base.MauserBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.M5Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.M5Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.M4Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.M1905Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.M1917Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetLeftLeg"].weapons,"Base.MauserBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.M5Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.M5Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.M4Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.M1905Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.M1917Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetRightLeg"].weapons,"Base.MauserBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.M5Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.M5Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.M4Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.M1905Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.M1917Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetShoulder"].weapons,"Base.MauserBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M5Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M5Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M4Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M1905Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M1917Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.MauserBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M5Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M4Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M6Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.M9Bayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["BayonetStomach"].weapons,"Base.AKBayonet")
    table.insert(AttachedWeaponDefinitions["armyknivesBeltGuns93"].weapons,"Base.M9Bayonet")
end

if not SandboxVars.Guns93.Guns93ZedGuns then
    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns9322LRAmmoDistro then
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Rug1022")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win69")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Marlin60")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Marlin39A")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win61")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Rug1022")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win69")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Marlin60")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Marlin39A")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win61")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns9325ACPAmmoDistro then
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Raven25")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Bobcat")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Raven25")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Bobcat")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Raven25")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Bobcat")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Raven25")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Bobcat")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns93380ACPAmmoDistro then
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.PPK")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Hammerless")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.P380")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.PPK")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Hammerless")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.P380")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns9338SPCAmmoDistro then
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.SW10")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.SW10")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Revolver_Short")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Revolver_Short")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.ColtDet")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.SW10")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.SW10")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Revolver_Short")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.ColtDet")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.SW10")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.SW10")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.SW10")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.SW10")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Revolver_Short")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.ColtDet")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns939mmAmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Uzi")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.BHP")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Beretta92FS")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Beretta92FS")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Glock17")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Glock17")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.SW5906")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.SW5906")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.P226")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.P228")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.RugP89")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.RugP89")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.P7M8")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.P7M13")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.USP9")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.CZ75B")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.TEC9")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.CalicoRifle")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.Uzi")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.BHP")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Glock17")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.SW5906")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.P226")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.P228")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.RugP89")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.TEC9")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.CalicoPistol")    
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Uzi")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.CZ75B")
        table.insert(AttachedWeaponDefinitions["handgunArmyGuns93"].weapons,"Base.Pistol")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.BHP")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.Beretta92FS")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.Glock17")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.SW5906")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.P226")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.P228")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.Glock17")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.SW5906")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.P226")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.P228")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns939mmAmmoDistro or not SandboxVars.Guns93.GunsAutoDistro then
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.MP5")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.M635")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns9340SWAmmoDistro then
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Glock22")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Glock22")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.SW4006")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.SW4006")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.USP40")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.SW4006")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Glock22")    
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.SW4006")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.Glock22")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns9345ACPAmmoDistro then
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Gov1911")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Revolver")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Command1911")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Officer1911")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Glock21")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.SW4506")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.SW4506")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.RugP90")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.RugP90")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Longslide")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.MAC10")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Gov1911")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Revolver")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Command1911")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Officer1911")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Glock21")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.SW4506")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.RugP90")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.MAC10")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Longslide")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.Gov1911")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.Glock21")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.SW4506")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.SW4506")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.Glock21")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.Glock21")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns9345ACPAmmoDistro or not SandboxVars.Guns93.GunsAutoDistro then
        table.insert(AttachedWeaponDefinitions["RarelongGunArmyGuns93"].weapons,"Base.M3GreaseGunFold")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns9345ColtAmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Win9445")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.ColtArmy")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win9445")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win9445")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.Win9445")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.ColtArmy")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns9310mmAmmoDistro then
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.DeltaElite")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Glock20")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Glock20")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Javelina")    
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.DeltaElite")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Glock20")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Javelina")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns93357MAGAmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Win94357")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.SW586")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.GP100")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.GP101")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.GP100")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.GP101")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.SecuritySix")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Python")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win94357")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win94357")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.Win94357")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.SW586")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.GP100")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.GP101")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.GP100")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.GP101")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.SecuritySix")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Python")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.SW586")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.SW586")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.SecuritySix")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.SecuritySix")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.Python")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns9344MAGAmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Marlin33644")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Pistol3")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Revolver_Long")
        table.insert(AttachedWeaponDefinitions["handgunSurvivorGuns93"].weapons,"Base.Anaconda")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Marlin33644")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Marlin33644")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.Marlin33644")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Revolver_Long")
        table.insert(AttachedWeaponDefinitions["handgunBikerGuns93"].weapons,"Base.Anaconda")
        table.insert(AttachedWeaponDefinitions["policeHandgunGuns93"].weapons,"Base.Revolver_Long")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns93223556AmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.AR15")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.CAR15")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.AR15")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.CAR15")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Mini14")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Mini14")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.AR180")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.AR180")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.VarmintRifle")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.R223Rem788")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.R223RugM77")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.W223WinM70")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Rem223760")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Mini14")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.AR15")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.CAR15")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.Mini14")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.AR180")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.AR15")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.AR15")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.CAR15")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.Mini14")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.Mini14")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns93223556AmmoDistro or not SandboxVars.Guns93.Guns93AutoDistro then
        table.insert(AttachedWeaponDefinitions["longGunArmyGuns93"].weapons,"Base.AssaultRifle")
        table.insert(AttachedWeaponDefinitions["RarelongGunArmyGuns93"].weapons,"Base.AssaultRifle")
        table.insert(AttachedWeaponDefinitions["RarelongGunArmyGuns93"].weapons,"Base.AssaultRifle")
        table.insert(AttachedWeaponDefinitions["RarelongGunArmyGuns93"].weapons,"Base.AssaultRifle")
        table.insert(AttachedWeaponDefinitions["RarelongGunArmyGuns93"].weapons,"Base.AssaultRifle")
        table.insert(AttachedWeaponDefinitions["RarelongGunArmyGuns93"].weapons,"Base.M723")
        table.insert(AttachedWeaponDefinitions["RarelongGunArmyGuns93"].weapons,"Base.M733")
        table.insert(AttachedWeaponDefinitions["RarelongGunArmyGuns93"].weapons,"Base.M249")
        table.insert(AttachedWeaponDefinitions["RarelongGunArmyGuns93"].weapons,"Base.M249")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns9330CARAmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.M1Carbine")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.M1Carbine")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.M1Carbine")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.M1Carbine")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns933030AmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Win943030")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Marlin3363030")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Marlin3363030")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win943030")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Marlin3363030")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win943030")    
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.Marlin3363030")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.Win943030")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns93762x39AmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.SKS")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.SKS")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Mini30")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.AKM")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.AKM")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.T56")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.AKMSFold")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.SKS")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Mini30")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.SKS")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.AKM")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.T56")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.AKMSFold")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns93308AmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.HuntingRifle")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.R308RugM77")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.W308WinM70")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.M1A")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.M1A")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.HK91")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.FAL")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.FAL")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.R308Rem700")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.HuntingRifle")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.R308RugM77")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.W308WinM70")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Brown308BAR")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win3087400")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Rem308760")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.M1A")    
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.HK91")
        table.insert(AttachedWeaponDefinitions["rareSurvivorLongGunGuns93"].weapons,"Base.FAL")
        table.insert(AttachedWeaponDefinitions["ArmySniperGuns93"].weapons,"Base.M24")
        table.insert(AttachedWeaponDefinitions["ArmySniperGuns93"].weapons,"Base.M24")
        table.insert(AttachedWeaponDefinitions["ArmySniperGuns93"].weapons,"Base.M14Rail")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.AssaultRifle2")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.M14Rail")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.M1A")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.R308Rem700")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.W308WinM70")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns93308AmmoDistro or not SandboxVars.Guns93.Guns93AutoDistro then
        table.insert(AttachedWeaponDefinitions["RarelongGunArmyGuns93"].weapons,"Base.M60")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns933006AmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.R3006Rem700")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.R3006RugM77")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.M1Garand")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.M1Garand")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.W3006WinM70")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.R3006Rem700")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.W3006WinM70")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Brown3006BAR")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win30067400")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Rem3006760")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns93MauserAmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Mauser98K")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Mauser98K")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.M1903")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.M1903")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.M1917")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.M1917")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns93ShotgunAmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Rem870P")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Moss590")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Win1912")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Win1200")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Win1200Def")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Ithaca37Riot")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.DoubleBarrelShotgun")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.SavageFox")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.DoubleBarrelShotgun")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.SavageFox")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Shotgun")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Moss500")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Shotgun")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Moss500")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win1912")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win1200")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win1200Def")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Ithaca37")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Ithaca37Riot")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Auto5")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.BenelliM3")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win1400")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Beretta682")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.BrownCitori")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.L395K")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win37")
        table.insert(AttachedWeaponDefinitions["longGunArmyGuns93"].weapons,"Base.M870")
        table.insert(AttachedWeaponDefinitions["longGunArmyGuns93"].weapons,"Base.M590")
        table.insert(AttachedWeaponDefinitions["policeShotgunsGuns93"].weapons,"Base.Rem870P")
        table.insert(AttachedWeaponDefinitions["policeShotgunsGuns93"].weapons,"Base.Moss590")
        table.insert(AttachedWeaponDefinitions["policeShotgunsGuns93"].weapons,"Base.Rem870P")
        table.insert(AttachedWeaponDefinitions["policeShotgunsGuns93"].weapons,"Base.Moss590")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.SPAS12Fold")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.Rem870P")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.Moss590")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.Rem870P")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.Moss590")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.Ithaca37Riot")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.Ithaca37Riot")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.BenelliM3")
    end

    if not SandboxVars.Guns93.Guns93ZedGuns or not SandboxVars.Guns93.Guns93SlugsAmmoDistro then
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Rem870PSlug")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Moss590Slug")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Win1912Slug")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Win1200Slug")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Win1200DefSlug")
        table.insert(AttachedWeaponDefinitions["militiaLongGunGuns93"].weapons,"Base.Ithaca37RiotSlug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.SavageFoxSlug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Rem870Slug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Rem870PSlug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Moss500Slug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Moss590Slug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win1912Slug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win1200Slug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win1200DefSlug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Ithaca37Slug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Ithaca37RiotSlug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Auto5Slug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win1400Slug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Beretta682Slug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.BrownCitoriSlug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.L395KSlug")
        table.insert(AttachedWeaponDefinitions["survivorLongGunGuns93"].weapons,"Base.Win37Slug")
        table.insert(AttachedWeaponDefinitions["longGunArmyGuns93"].weapons,"Base.M870Slug")
        table.insert(AttachedWeaponDefinitions["longGunArmyGuns93"].weapons,"Base.M590Slug")
        table.insert(AttachedWeaponDefinitions["policeShotgunsGuns93"].weapons,"Base.Rem870PSlug")
        table.insert(AttachedWeaponDefinitions["policeShotgunsGuns93"].weapons,"Base.Moss590Slug")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.Moss590Slug")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.Rem870PSlug")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.Ithaca37RiotSlug")
        table.insert(AttachedWeaponDefinitions["policeLongGunGuns93"].weapons,"Base.BenelliM3Slug")
    end
end