require 'Items/SuburbsDistributions'
require 'Items/Distributions'
require 'Items/ProceduralDistributions'
require "Definitions/AttachedWeaponDefinitions"

-- This overwrites the table. 
WeaponUpgrades = {
	-- Shotguns
    Shotgun = {"IronSightGhost", "IronSightNotch", "ChokeTubeFull", "ChokeTubeImproved", "ChokeTubeRifled", "RecoilPad", "RecoilPadAlt"},
	Rem870P = {"IronSightGhost", "IronSightNotch", "Sling", "RecoilPad", "ShellCarrier", "RecoilPadAlt"},
	M870 = {"IronSightGhost", "IronSightNotch", "Sling", "RecoilPad", "ShellCarrier", "RecoilPadAlt"},
	DoubleBarrelShotgun = {"ChokeTubeFull", "ChokeTubeImproved", "RecoilPad", "RecoilPadAlt"},
	SavageFox = {"ChokeTubeFull", "ChokeTubeImproved", "RecoilPad", "RecoilPadAlt"},
	BrownCitori = {"ChokeTubeFull", "ChokeTubeImproved", "RecoilPad", "RecoilPadAlt"},
	Beretta682 = {"ChokeTubeFull", "ChokeTubeImproved", "RecoilPad", "RecoilPadAlt"},
	Moss500 = {"IronSightGhost", "IronSightNotch", "ChokeTubeFull", "ChokeTubeImproved", "ChokeTubeRifled", "RecoilPad", "RecoilPadAlt"}, 
	Moss590 = {"IronSightGhost", "IronSightNotch", "Sling", "RecoilPad", "RecoilPadAlt"}, 
	M590 = {"IronSightGhost", "IronSightNotch", "Sling", "RecoilPad", "ShellCarrier", "RecoilPadAlt"},
	Win1200Def = {"IronSightGhost", "IronSightNotch", "Sling", "RecoilPad", "ShellCarrier", "RecoilPadAlt"},
	Win1912 = {"IronSightGhost", "IronSightNotch", "ChokeTubeFull", "ChokeTubeImproved", "RecoilPad", "RecoilPadAlt"},
	Win1200 = {"IronSightGhost", "IronSightNotch", "ChokeTubeFull", "ChokeTubeImproved", "RecoilPad", "RecoilPadAlt"},  
	Ithaca37 = {"IronSightGhost", "IronSightNotch", "ChokeTubeFull", "ChokeTubeImproved", "RecoilPad", "ShellCarrier", "RecoilPadAlt"}, 
	Ithaca37Riot = {"IronSightGhost", "IronSightNotch", "Sling", "RecoilPad", "ShellCarrier", "RecoilPadAlt"},
	Auto5 = {"IronSightGhost", "IronSightNotch", "ChokeTubeFull", "ChokeTubeImproved", "RecoilPad", "RecoilPadAlt"}, 
	BenelliM3 = {"IronSightGhost", "IronSightNotch", "RecoilPad", "ShellCarrier", "RecoilPadAlt"}, 
	Win1400 = {"IronSightGhost", "IronSightNotch", "ChokeTubeFull", "ChokeTubeImproved", "RecoilPad", "ShellCarrier", "RecoilPadAlt"},
	L395K = {"ChokeTubeFull", "ChokeTubeImproved", "RecoilPad", "RecoilPadAlt"},
	Win37 = {"ChokeTubeFull", "ChokeTubeImproved", "RecoilPad", "RecoilPadAlt"},
	SPAS12 = {"Sling"},
	-- Rifles and Carbines
	R223Rem788 = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "ODAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
    HuntingRifle = {"x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "ODAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	R3006Rem700 = {"x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "ODAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	R308Rem700 = {"x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "ODAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	VarmintRifle = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "ODAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	W3006WinM70 = {"x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "ODAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	W308WinM70 = {"x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "ODAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	W223WinM70 = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "ODAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	R3006RugM77 = {"x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "ODAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	R308RugM77 = {"x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "ODAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	R223RugM77 = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Brown3006BAR = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Brown308BAR = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Win30067400 = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Win3087400 = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Rem3006760 = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Rem308760 = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Rem223760 = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	M24 = {"ARTScope", "Sling", "RecoilPad", "NylonAmmoCarrier", "ODAmmoCarrier", "RecoilPadAlt"},
	AssaultRifle = {"Sling", "x4Handle", "x3Handle"},
	M723 = {"Sling", "x4Handle", "x3Handle"},
	M733 = {"Sling", "x4Handle", "x3Handle"},
	M635 = {"Sling"},
	AssaultRifle2 = {"Sling", "M14ARTScope"},
	M1A = {"Sling"},
	M14Rail = {"RedDot", "x6Scope", "x8Scope", "x10Scope", "aaa", "Sling", "30Silencer"},
	M16Rail = {"RedDot", "x6Scope", "x8Scope", "x10Scope", "ARTScope", "Sling"},
	M723Rail = {"RedDot", "Sling", "556Silencer"},
	M733Rail = {"RedDot", "Sling", "556Silencer"},
	M249 = {"Sling"},
	M60 = {"Sling"},
	AR15 = {"Sling", "x4Handle", "x3Handle"},
	CAR15 = {"Sling", "x4Handle", "x3Handle"},
	M1Carbine = {"Sling"},
	M1Garand = {"Sling"},
	M1903 = {"Sling"},
	Mauser98K = {"Sling"},
	SKS = {"Sling"},
	Mini14 = {"Sling"},
	Mini14Rail = {"AccuDot", "x4Scope", "x6Scope", "x8Scope", "Sling"},
	Mini30 = {"Sling"},
	Mini30Rail = {"AccuDot", "x4Scope", "x6Scope", "Sling"},
	AR180 = {"Sling"},
	Marlin9 = {"AccuDot", "x2Scope", "x3Scope", "x4Scope", "x6Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Marlin45 = {"AccuDot", "x2Scope", "x3Scope", "x4Scope", "x6Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	MP5 = {"Sling"},
	CalicoRifle = {"Sling"},
	Rug1022 = {"AccuDot", "x2Scope", "x3Scope", "x4Scope", "x6Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Win69 = {"AccuDot", "x2Scope", "x3Scope", "x4Scope", "x6Scope", "Sling", "RecoilPad", "IronSightPeep"},
	Marlin39A = {"AccuDot", "x2Scope", "x3Scope", "x4Scope", "x6Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Marlin60 = {"AccuDot", "x2Scope", "x3Scope", "x4Scope", "x6Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Win61 = {"AccuDot", "x2Scope", "x3Scope", "x4Scope", "x6Scope", "Sling", "RecoilPad", "IronSightPeep", "RecoilPadAlt"},
	Marlin3363030 = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	Marlin33644 = {"x2Scope", "x4Scope", "x6Scope", "x8Scope", "x10Scope", "Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	Win943030 = {"Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	Win94357 = {"Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	Win9445 = {"Sling", "RecoilPad", "IronSightPeep", "NylonAmmoCarrier", "LeatherAmmoCarrier", "RecoilPadAlt"},
	Uzi = {"Sling"},
	AKM = {"Sling"},
	AKMSFold = {"Sling"},
	T56 = {"Sling"},
	FAL = {"Sling"},
	HK91 = {"Sling"},
	M3GreaseGunFold = {"Sling"},
	Valmet = {"Sling"},

	-- Pistols
	Beretta92FS = {"IronPistolTarget", "IronPistolCombat"},
	Gov1911 = {"IronPistolTarget", "IronPistolCombat"},
	Pistol3 = {"IronPistolTarget", "IronPistolCombat"},
	BHP = {"IronPistolTarget", "IronPistolCombat"},
	Revolver = {"IronRevolverTarget", "IronRevolverCombat"},
	SW625Clip = {"IronRevolverTarget", "IronRevolverCombat"},
	Revolver_Long = {"IronRevolverTarget", "IronRevolverCombat"},
	SW17 = {"IronRevolverTarget"},
	SW586 = {"IronRevolverTarget", "IronRevolverCombat"},
	GP100 = {"IronRevolverTarget", "IronRevolverCombat"},
	SecuritySix = {"IronRevolverTarget", "IronRevolverCombat"},
	Python = {"IronRevolverTarget", "IronRevolverCombat"},
	Anaconda = {"IronRevolverTarget", "IronRevolverCombat"},
	Command1911 = {"IronPistolTarget", "IronPistolCombat"},
	Officer1911 = {"IronPistolTarget", "IronPistolCombat"},
	DeltaElite = {"IronPistolTarget", "IronPistolCombat"},
	Longslide = {"IronPistolTarget", "IronPistolCombat", "1911Comp"},
	Javelina = {"IronPistolTarget", "IronPistolCombat", "1911Comp"},
	Glock17 = {"IronPistolTarget", "IronPistolCombat"},
	Glock20 = {"IronPistolTarget", "IronPistolCombat"},
	Glock21 = {"IronPistolTarget", "IronPistolCombat"},
	Glock22 = {"IronPistolTarget", "IronPistolCombat"},
	SW5906 = {"IronPistolTarget", "IronPistolCombat"},
	SW4506 = {"IronPistolTarget", "IronPistolCombat"},
	SW4006 = {"IronPistolTarget", "IronPistolCombat"},
	RugP89 = {"IronPistolTarget", "IronPistolCombat"},
	RugP90 = {"IronPistolTarget", "IronPistolCombat"},
	P226 = {"IronPistolTarget", "IronPistolCombat"},
	P228 = {"IronPistolTarget", "IronPistolCombat"},
	P7M8 = {"IronPistolTarget", "IronPistolCombat"},
	P7M13 = {"IronPistolTarget", "IronPistolCombat"},
	USP40 = {"IronPistolTarget", "IronPistolCombat"},
	USP9 = {"IronPistolTarget", "IronPistolCombat"},
	CZ75B = {"IronPistolTarget", "IronPistolCombat"},
	Buckmark = {"IronPistolTarget"},
	Rugmark = {"IronPistolTarget"},
}

Events.OnPreDistributionMerge.Add(modifyAllLootTables)