require "Items/Distributions.lua"
require "Items/ProceduralDistributions.lua"
require "Items/SuburbsDistributions.lua"
require "Vehicles/VehicleDistributions.lua"

if SandboxVars.Guns93.Guns93357MAGAmmoDistro and not SandboxVars.Guns93.Guns9338SPCAmmoDistro then---
table.insert(ProceduralDistributions.list.BedroomDresser.junk.items,"SW586Spc")
table.insert(ProceduralDistributions.list.BedroomDresser.junk.items,0.192 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.BedroomDresser.junk.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.BedroomDresser.junk.items,0.16 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.BedroomDresser.junk.items,"GP100Spc")
table.insert(ProceduralDistributions.list.BedroomDresser.junk.items,0.224 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.BedroomSideTable.junk.items,"SW65Spc")
table.insert(ProceduralDistributions.list.BedroomSideTable.junk.items,0.256 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.BedroomSideTable.junk.items,"GP101Spc")
table.insert(ProceduralDistributions.list.BedroomSideTable.junk.items,0.192 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.BedroomSideTable.junk.items,"PythonSpc")
table.insert(ProceduralDistributions.list.BedroomSideTable.junk.items,0.16 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,"SW65Spc")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,0.16 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,"SW586Spc")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,0.12 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,0.1 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,"Win94357Spc")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,0.16 * SandboxVars.Guns93.Guns93RifleRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"SW65Spc")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.256 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"SW586Spc")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.192 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"GP100Spc")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.224 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"GP101Spc")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.192 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"PythonSpc")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.16 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"SW65Spc")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.256 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"SW586Spc")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.192 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"GP100Spc")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.224 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"GP101Spc")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.192 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"PythonSpc")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.16 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"SW65Spc")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.64 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"GP100Spc")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.56 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"PythonSpc")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"Win94357Spc")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.64 * SandboxVars.Guns93.Guns93RifleRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"SW65Spc")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,3.2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"SW586Spc")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"GP100Spc")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.8 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"GP101Spc")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"PythonSpc")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Win94357Spc")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,3.2 * SandboxVars.Guns93.Guns93RifleRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"SW65Spc")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,3.2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"SW586Spc")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"GP100Spc")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.8 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"GP101Spc")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"PythonSpc")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Win94357Spc")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,3.2 * SandboxVars.Guns93.Guns93RifleRarity)
table.insert(ProceduralDistributions.list.HuntingLockers.items,"Win94357Spc")
table.insert(ProceduralDistributions.list.HuntingLockers.items,0.32 * SandboxVars.Guns93.Guns93RifleRarity)
table.insert(ProceduralDistributions.list.KitchenRandom.items,"SW65Spc")
table.insert(ProceduralDistributions.list.KitchenRandom.items,0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.KitchenRandom.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.KitchenRandom.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.KitchenRandom.items,"GP101Spc")
table.insert(ProceduralDistributions.list.KitchenRandom.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.KitchenRandom.items,"PythonSpc")
table.insert(ProceduralDistributions.list.KitchenRandom.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,"SW65Spc")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,0.016 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,"SW586Spc")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,0.012 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,0.01 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,"GP100Spc")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,0.014 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,"GP101Spc")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,0.012 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,"PythonSpc")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk.items,0.01 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"SW65Spc")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.64 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"SW586Spc")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.48 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"GP100Spc")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.56 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"GP101Spc")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.48 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"PythonSpc")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Win94357Spc")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.64 * SandboxVars.Guns93.Guns93RifleRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"SW65Spc")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.64 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"SW586Spc")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.48 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"GP100Spc")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.56 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"GP101Spc")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.48 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"PythonSpc")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Win94357Spc")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.64 * SandboxVars.Guns93.Guns93RifleRarity)
table.insert(ProceduralDistributions.list.PlankStashGun.items,"SW65Spc")
table.insert(ProceduralDistributions.list.PlankStashGun.items,0.64 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PlankStashGun.items,"SW586Spc")
table.insert(ProceduralDistributions.list.PlankStashGun.items,0.48 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PlankStashGun.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.PlankStashGun.items,0.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PlankStashGun.items,"GP100Spc")
table.insert(ProceduralDistributions.list.PlankStashGun.items,0.56 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PlankStashGun.items,"GP101Spc")
table.insert(ProceduralDistributions.list.PlankStashGun.items,0.48 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PlankStashGun.items,"PythonSpc")
table.insert(ProceduralDistributions.list.PlankStashGun.items,0.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(SuburbsDistributions.GunCache2.Bag_DuffelBagTINT.items,"SW586Spc")
table.insert(SuburbsDistributions.GunCache2.Bag_DuffelBagTINT.items,16.8 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,"SW65Spc")
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,3.2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,"SW586Spc")
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,2.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,"PythonSpc")
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PoliceDesk.items,"SW65Spc")
table.insert(ProceduralDistributions.list.PoliceDesk.items,0.32 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PoliceDesk.items,"SW586Spc")
table.insert(ProceduralDistributions.list.PoliceDesk.items,0.24 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.PoliceDesk.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.PoliceDesk.items,0.2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.SecurityLockers.items,"SW65Spc")
table.insert(ProceduralDistributions.list.SecurityLockers.items,3.2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.SecurityLockers.items,"SW586Spc")
table.insert(ProceduralDistributions.list.SecurityLockers.items,2.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.SecurityLockers.items,"SecuritySixSpc")
table.insert(ProceduralDistributions.list.SecurityLockers.items,2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.SecurityLockers.items,"GP100Spc")
table.insert(ProceduralDistributions.list.SecurityLockers.items,2.8 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"Win94357Spc")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.0064 * SandboxVars.Guns93.Guns93RifleRarity)
table.insert(ProceduralDistributions.list.Trapper.items,"Win94357Spc")
table.insert(ProceduralDistributions.list.Trapper.items,0.0064 * SandboxVars.Guns93.Guns93RifleRarity)
table.insert(SuburbsDistributions.Bag_WeaponBag.items,"SW65Spc")
table.insert(SuburbsDistributions.Bag_WeaponBag.items,9.6 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(SuburbsDistributions.Bag_WeaponBag.items,"SW586Spc")
table.insert(SuburbsDistributions.Bag_WeaponBag.items,7.2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(SuburbsDistributions.Bag_WeaponBag.items,"GP100Spc")
table.insert(SuburbsDistributions.Bag_WeaponBag.items,8.4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(SuburbsDistributions.Bag_WeaponBag.items,"GP101Spc")
table.insert(SuburbsDistributions.Bag_WeaponBag.items,7.2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(SuburbsDistributions.Bag_WeaponBag.items,"PythonSpc")
table.insert(SuburbsDistributions.Bag_WeaponBag.items,6 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(SuburbsDistributions.GunCache1.GunBox.items,"SW65Spc")
table.insert(SuburbsDistributions.GunCache1.GunBox.items,19.2 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(SuburbsDistributions.GunCache1.counter.items,"SecuritySixSpc")
table.insert(SuburbsDistributions.GunCache1.counter.items,4 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(SuburbsDistributions.GunCache1.Bag_DuffelBagTINT.items,"SW65Spc")
table.insert(SuburbsDistributions.GunCache1.Bag_DuffelBagTINT.items,32 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"Win94357Spc")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.32 * SandboxVars.Guns93.Guns93RifleRarity)
table.insert(VehicleDistributions.MetalWelderGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.MetalWelderGloveBox.junk.items,0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.MetalWelderGloveBox.junk.items,"SW586Spc")
table.insert(VehicleDistributions.MetalWelderGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.MetalWelderGloveBox.junk.items,"PythonSpc")
table.insert(VehicleDistributions.MetalWelderGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.RadioGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.RadioGloveBox.junk.items,0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.RadioGloveBox.junk.items,"GP100Spc")
table.insert(VehicleDistributions.RadioGloveBox.junk.items,0.0056 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.RadioGloveBox.junk.items,"GP101Spc")
table.insert(VehicleDistributions.RadioGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PainterGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.PainterGloveBox.junk.items,0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PainterGloveBox.junk.items,"SW586Spc")
table.insert(VehicleDistributions.PainterGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PainterGloveBox.junk.items,"SecuritySixSpc")
table.insert(VehicleDistributions.PainterGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PainterGloveBox.junk.items,"GP100Spc")
table.insert(VehicleDistributions.PainterGloveBox.junk.items,0.0056 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PainterGloveBox.junk.items,"GP101Spc")
table.insert(VehicleDistributions.PainterGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PainterGloveBox.junk.items,"PythonSpc")
table.insert(VehicleDistributions.PainterGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.ConstructionWorkerGloveBox.junk.items, "SW65Spc")
table.insert(VehicleDistributions.ConstructionWorkerGloveBox.junk.items, 0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.ConstructionWorkerGloveBox.junk.items, "SW586Spc")
table.insert(VehicleDistributions.ConstructionWorkerGloveBox.junk.items, 0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.ConstructionWorkerGloveBox.junk.items, "SecuritySixSpc")
table.insert(VehicleDistributions.ConstructionWorkerGloveBox.junk.items, 0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.ConstructionWorkerGloveBox.junk.items, "GP100Spc")
table.insert(VehicleDistributions.ConstructionWorkerGloveBox.junk.items, 0.0056 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.ConstructionWorkerGloveBox.junk.items, "PythonSpc")
table.insert(VehicleDistributions.ConstructionWorkerGloveBox.junk.items, 0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PoliceGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.PoliceGloveBox.junk.items,1.6 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PoliceGloveBox.junk.items,"SecuritySixSpc")
table.insert(VehicleDistributions.PoliceGloveBox.junk.items,1 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.HunterGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.HunterGloveBox.junk.items,0.0256 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.HunterGloveBox.junk.items,"PythonSpc")
table.insert(VehicleDistributions.HunterGloveBox.junk.items,0.016 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.HunterTruckBed.items,"Win94357Spc")
table.insert(VehicleDistributions.HunterTruckBed.items,0.0064 * SandboxVars.Guns93.Guns93RifleRarity)
table.insert(VehicleDistributions.FireGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.FireGloveBox.junk.items,0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.FireGloveBox.junk.items,"SW586Spc")
table.insert(VehicleDistributions.FireGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.FireGloveBox.junk.items,"SecuritySixSpc")
table.insert(VehicleDistributions.FireGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.FireGloveBox.junk.items,"GP100Spc")
table.insert(VehicleDistributions.FireGloveBox.junk.items,0.0056 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.FireGloveBox.junk.items,"PythonSpc")
table.insert(VehicleDistributions.FireGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.McCoyGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.McCoyGloveBox.junk.items,0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.McCoyGloveBox.junk.items,"SecuritySixSpc")
table.insert(VehicleDistributions.McCoyGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.FossoilGloveBox.junk.items,"SW586Spc")
table.insert(VehicleDistributions.FossoilGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.FossoilGloveBox.junk.items,"SecuritySixSpc")
table.insert(VehicleDistributions.FossoilGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.FossoilGloveBox.junk.items,"GP100Spc")
table.insert(VehicleDistributions.FossoilGloveBox.junk.items,0.0056 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.FossoilGloveBox.junk.items,"PythonSpc")
table.insert(VehicleDistributions.FossoilGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PostalGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.PostalGloveBox.junk.items,0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PostalGloveBox.junk.items,"SW586Spc")
table.insert(VehicleDistributions.PostalGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PostalGloveBox.junk.items,"SecuritySixSpc")
table.insert(VehicleDistributions.PostalGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PostalGloveBox.junk.items,"GP100Spc")
table.insert(VehicleDistributions.PostalGloveBox.junk.items,0.0056 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.PostalGloveBox.junk.items,"PythonSpc")
table.insert(VehicleDistributions.PostalGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.SpiffoGloveBox.junk.items, "SW65Spc")
table.insert(VehicleDistributions.SpiffoGloveBox.junk.items, 0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.SpiffoGloveBox.junk.items, "SecuritySixSpc")
table.insert(VehicleDistributions.SpiffoGloveBox.junk.items, 0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.SpiffoGloveBox.junk.items, "GP100Spc")
table.insert(VehicleDistributions.SpiffoGloveBox.junk.items, 0.0056 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.SpiffoGloveBox.junk.items, "PythonSpc")
table.insert(VehicleDistributions.SpiffoGloveBox.junk.items, 0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.MassGenFacGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.MassGenFacGloveBox.junk.items,0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.MassGenFacGloveBox.junk.items,"SW586Spc")
table.insert(VehicleDistributions.MassGenFacGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.MassGenFacGloveBox.junk.items,"GP101Spc")
table.insert(VehicleDistributions.MassGenFacGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.MassGenFacGloveBox.junk.items,"PythonSpc")
table.insert(VehicleDistributions.MassGenFacGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.TransitGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.TransitGloveBox.junk.items,0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.TransitGloveBox.junk.items,"GP101Spc")
table.insert(VehicleDistributions.TransitGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.DistilleryGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.DistilleryGloveBox.junk.items,0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.DistilleryGloveBox.junk.items,"PythonSpc")
table.insert(VehicleDistributions.DistilleryGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.HeraldsGloveBox.junk.items,"SW65Spc")
table.insert(VehicleDistributions.HeraldsGloveBox.junk.items,0.0064 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.HeraldsGloveBox.junk.items,"SW586Spc")
table.insert(VehicleDistributions.HeraldsGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.HeraldsGloveBox.junk.items,"GP101Spc")
table.insert(VehicleDistributions.HeraldsGloveBox.junk.items,0.0048 * SandboxVars.Guns93.Guns93RevolverRarity)
table.insert(VehicleDistributions.HeraldsGloveBox.junk.items,"PythonSpc")
table.insert(VehicleDistributions.HeraldsGloveBox.junk.items,0.004 * SandboxVars.Guns93.Guns93RevolverRarity)
end---
if SandboxVars.Guns93.Guns93ShotgunAmmoDistro and not SandboxVars.Guns93.Guns93SlugsAmmoDistro then---
table.insert(ProceduralDistributions.list.ArmyStorageGuns.items,"M870Slug")
table.insert(ProceduralDistributions.list.ArmyStorageGuns.items,4.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.ArmyStorageGuns.items,"M590Slug")
table.insert(ProceduralDistributions.list.ArmyStorageGuns.items,3 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,0.14 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,0.16 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,0.12 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,0.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,"L395KSlug")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.junk.items,0.16 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.256 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.224 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.256 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"L395KSlug")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.256 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"Win37Slug")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.352 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugLabGuns.items,"Win1200Slug")
table.insert(ProceduralDistributions.list.DrugLabGuns.items,0.192 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.256 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.224 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.256 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"L395KSlug")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.256 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"Win37Slug")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.352 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,"Win1200Slug")
table.insert(ProceduralDistributions.list.DrugShackWeapons.items,0.192 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.56 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.64 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.48 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"Win1400Slug")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"L395KSlug")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.64 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.FirearmWeapons.items,"Win1200Slug")
table.insert(ProceduralDistributions.list.FirearmWeapons.items,0.48 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GarageFirearms.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.GarageFirearms.items,0.224 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GarageFirearms.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.GarageFirearms.items,0.224 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GarageFirearms.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.GarageFirearms.items,0.256 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GarageFirearms.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.GarageFirearms.items,0.192 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GarageFirearms.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.GarageFirearms.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GarageFirearms.items,"L395KSlug")
table.insert(ProceduralDistributions.list.GarageFirearms.items,0.256 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GarageFirearms.items,"Win1200Slug")
table.insert(ProceduralDistributions.list.GarageFirearms.items,0.192 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,3.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Rem870PSlug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Moss590Slug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,3.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Ithaca37RiotSlug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"BenelliM3Slug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,1.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Win1400Slug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Beretta682Slug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"BrownCitoriSlug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"L395KSlug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,3.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"L395KMagSlug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,1.2 * SandboxVars.Guns93.Guns93MagazineRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Win37Slug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,4.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Win1200Slug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,"Win1200DefSlug")
table.insert(ProceduralDistributions.list.GunStoreCounter.junk.items,2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,3.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Rem870PSlug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Moss590Slug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,3.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Ithaca37RiotSlug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"BenelliM3Slug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,1.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Win1400Slug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Beretta682Slug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"BrownCitoriSlug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"L395KSlug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,3.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Win37Slug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,4.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Win1200Slug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,"Win1200DefSlug")
table.insert(ProceduralDistributions.list.GunStoreDisplayCase.junk.items,2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.GunStoreShelf.items,"L395KMagSlug")
table.insert(ProceduralDistributions.list.GunStoreShelf.items,1.2 * SandboxVars.Guns93.Guns93MagazineRarity)
table.insert(ProceduralDistributions.list.HuntingLockers.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.HuntingLockers.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.HuntingLockers.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.HuntingLockers.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.HuntingLockers.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.HuntingLockers.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.HuntingLockers.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.HuntingLockers.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.HuntingLockers.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.HuntingLockers.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.HuntingLockers.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.HuntingLockers.items,0.24 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.HuntingLockers.items,"Win1400Slug")
table.insert(ProceduralDistributions.list.HuntingLockers.items,0.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.HuntingLockers.items,"Beretta682Slug")
table.insert(ProceduralDistributions.list.HuntingLockers.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.HuntingLockers.items,"BrownCitoriSlug")
table.insert(ProceduralDistributions.list.HuntingLockers.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.HuntingLockers.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.HuntingLockers.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.BarCounterWeapon.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.BarCounterWeapon.items,1 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.BarCounterWeapon.items,"SOSavageFox")
table.insert(ProceduralDistributions.list.BarCounterWeapon.items,0.1 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.64 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.56 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Moss590Slug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.48 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.56 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.64 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.48 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Win1400Slug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Beretta682Slug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.56 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"L395KSlug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.64 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"L395KMagSlug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.24 * SandboxVars.Guns93.Guns93MagazineRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Win37Slug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.88 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Win1200Slug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.48 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,"Win1200DefSlug")
table.insert(ProceduralDistributions.list.PawnShopGuns.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.64 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.56 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Moss590Slug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.48 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.56 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.64 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.48 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Win1400Slug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Beretta682Slug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.56 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"L395KSlug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.64 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"L395KMagSlug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.24 * SandboxVars.Guns93.Guns93MagazineRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Win37Slug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.88 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Win1200Slug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.48 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,"Win1200DefSlug")
table.insert(ProceduralDistributions.list.PawnShopGunsSpecial.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.GunCache2.Bag_DuffelBagTINT.items,"Win1912Slug")
table.insert(SuburbsDistributions.GunCache2.Bag_DuffelBagTINT.items,19.6 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.ShotgunCache1.ShotgunBox.items,"Ithaca37Slug")
table.insert(SuburbsDistributions.ShotgunCache1.ShotgunBox.items,200 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.ShotgunCache1.ShotgunBox.items,"Win1200DefSlug")
table.insert(SuburbsDistributions.ShotgunCache1.ShotgunBox.items,125 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.ShotgunCache1.Bag_DuffelBagTINT.items,"SOMoss500")
table.insert(SuburbsDistributions.ShotgunCache1.Bag_DuffelBagTINT.items,200.1 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.ShotgunCache1.Bag_DuffelBagTINT.items,"SORem870")
table.insert(SuburbsDistributions.ShotgunCache1.Bag_DuffelBagTINT.items,200.1 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.ShotgunCache2.ShotgunBox.items,"Rem870Slug")
table.insert(SuburbsDistributions.ShotgunCache2.ShotgunBox.items,200 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.ShotgunCache2.ShotgunBox.items,"Moss590Slug")
table.insert(SuburbsDistributions.ShotgunCache2.ShotgunBox.items,150 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.ShotgunCache2.counter.items,"Rem870PSlug")
table.insert(SuburbsDistributions.ShotgunCache2.counter.items,19.6 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.ShotgunCache2.counter.items,"Auto5Slug")
table.insert(SuburbsDistributions.ShotgunCache2.counter.items,16.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.ShotgunCache2.counter.items,"L395KSlug")
table.insert(SuburbsDistributions.ShotgunCache2.counter.items,22.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,"Rem870PSlug")
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,"Moss590Slug")
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,"Ithaca37RiotSlug")
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,"BenelliM3Slug")
table.insert(ProceduralDistributions.list.PoliceStorageGuns.items,1.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.008 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.0064 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.0056 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"Moss590Slug")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.0048 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.0056 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.0064 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.0048 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"Win1400Slug")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.004 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.SurvivalGear.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.SurvivalGear.items,0.008 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.Trapper.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.Trapper.items,0.008 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.Trapper.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.Trapper.items,0.0064 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.Trapper.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.Trapper.items,0.0056 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.Trapper.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.Trapper.items,0.0056 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.Trapper.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.Trapper.items,0.0064 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.Trapper.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.Trapper.items,0.0048 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.Trapper.items,"Win1400Slug")
table.insert(ProceduralDistributions.list.Trapper.items,0.004 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.Trapper.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.Trapper.items,0.008 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.Bag_ShotgunDblSawnoffBag.items,"SOStoegerUplander")
table.insert(SuburbsDistributions.Bag_ShotgunDblSawnoffBag.items,200 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.Bag_ShotgunSawnoffBag.items,"SOAuto5")
table.insert(SuburbsDistributions.Bag_ShotgunSawnoffBag.items,200 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.Bag_ShotgunBag.items,"Moss590Slug")
table.insert(SuburbsDistributions.Bag_ShotgunBag.items,200.04 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.Bag_ShotgunDblBag.items,"Win37Slug")
table.insert(SuburbsDistributions.Bag_ShotgunDblBag.items,200.024 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.Bag_SurvivorBag.items,"SOMoss500")
table.insert(SuburbsDistributions.Bag_SurvivorBag.items,9 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.Bag_WeaponBag.items,"SOAuto5")
table.insert(SuburbsDistributions.Bag_WeaponBag.items,1.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.Bag_WeaponBag.items,"SORem870")
table.insert(SuburbsDistributions.Bag_WeaponBag.items,18 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(SuburbsDistributions.GunCache1.Bag_DuffelBagTINT.items,"Ithaca37Slug")
table.insert(SuburbsDistributions.GunCache1.Bag_DuffelBagTINT.items,32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,"Moss590Slug")
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,0.24 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,"L395KSlug")
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,"Win37Slug")
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,0.44 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,"Win1200DefSlug")
table.insert(ProceduralDistributions.list.WardrobeMan.junk.items,0.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,0.24 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,"Win1400Slug")
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,0.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,"BrownCitoriSlug")
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,"L395KSlug")
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,"Win37Slug")
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,0.44 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,"Win1200Slug")
table.insert(ProceduralDistributions.list.WardrobeManClassy.junk.items,0.24 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"Moss590Slug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.24 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"Auto5Slug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.24 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"Win1400Slug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"Beretta682Slug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"BrownCitoriSlug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"L395KSlug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"Win37Slug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.44 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"Win1200Slug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.24 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,"Win1200DefSlug")
table.insert(ProceduralDistributions.list.WardrobeRedneck.junk.items,0.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,"Beretta682Slug")
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,"BrownCitoriSlug")
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,"L395KSlug")
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,"Win37Slug")
table.insert(ProceduralDistributions.list.WardrobeWoman.junk.items,0.44 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"StoegerUplanderSlug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"Rem870Slug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"Moss500Slug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"Win1912Slug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"Ithaca37Slug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"Win1400Slug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"Beretta682Slug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"BrownCitoriSlug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.28 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"SavageFoxSlug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"L395KSlug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.32 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"Win37Slug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.44 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,"Win1200Slug")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.junk.items,0.24 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(VehicleDistributions.PoliceTruckBed.junk.items,"Rem870PSlug")
table.insert(VehicleDistributions.PoliceTruckBed.junk.items,2.8 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(VehicleDistributions.PoliceTruckBed.junk.items,"Moss590Slug")
table.insert(VehicleDistributions.PoliceTruckBed.junk.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(VehicleDistributions.PoliceTruckBed.junk.items,"Ithaca37RiotSlug")
table.insert(VehicleDistributions.PoliceTruckBed.junk.items,2.4 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(VehicleDistributions.PoliceTruckBed.junk.items,"BenelliM3Slug")
table.insert(VehicleDistributions.PoliceTruckBed.junk.items,1.2 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(VehicleDistributions.HunterTruckBed.items,"Rem870Slug")
table.insert(VehicleDistributions.HunterTruckBed.items,0.0064 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(VehicleDistributions.HunterTruckBed.items,"Moss500Slug")
table.insert(VehicleDistributions.HunterTruckBed.items,0.0056 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(VehicleDistributions.HunterTruckBed.items,"Ithaca37Slug")
table.insert(VehicleDistributions.HunterTruckBed.items,0.0064 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(VehicleDistributions.HunterTruckBed.items,"Auto5Slug")
table.insert(VehicleDistributions.HunterTruckBed.items,0.0048 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(VehicleDistributions.HunterTruckBed.items,"Win1400Slug")
table.insert(VehicleDistributions.HunterTruckBed.items,0.004 * SandboxVars.Guns93.Guns93ShotgunRarity)
table.insert(VehicleDistributions.HunterTruckBed.items,"SavageFoxSlug")
table.insert(VehicleDistributions.HunterTruckBed.items,0.008 * SandboxVars.Guns93.Guns93ShotgunRarity)
end