-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["GunshopCounters_0"] = {{ name = "other", tiles = {"GunshopCounters_32", "GunshopCounters_40"} }}
overlayMap["GunshopCounters_1"] = {{ name = "other", tiles = {"GunshopCounters_33", "GunshopCounters_41"} }}
overlayMap["GunshopCounters_2"] = {{ name = "other", tiles = {"GunshopCounters_34", "GunshopCounters_42"} }}
overlayMap["GunshopCounters_3"] = {{ name = "other", tiles = {"GunshopCounters_35", "GunshopCounters_43"} }}
overlayMap["GunshopCounters_4"] = {{ name = "other", tiles = {"GunshopCounters_36", "GunshopCounters_44"} }}
overlayMap["GunshopCounters_5"] = {{ name = "other", tiles = {"GunshopCounters_37", "GunshopCounters_45"} }}
overlayMap["GunshopCounters_6"] = {{ name = "other", tiles = {"GunshopCounters_38", "GunshopCounters_46"} }}
overlayMap["GunshopCounters_7"] = {{ name = "other", tiles = {"GunshopCounters_39", "GunshopCounters_47"} }}
overlayMap["GunshopCounters_8"] = {{ name = "other", tiles = {"GunshopCounters_16", "GunshopCounters_24"} }}
overlayMap["GunshopCounters_9"] = {{ name = "other", tiles = {"GunshopCounters_17", "GunshopCounters_25"} }}
overlayMap["GunshopCounters_10"] = {{ name = "other", tiles = {"GunshopCounters_18", "GunshopCounters_26"} }}
overlayMap["GunshopCounters_11"] = {{ name = "other", tiles = {"GunshopCounters_19", "GunshopCounters_27"} }}
overlayMap["GunshopCounters_12"] = {{ name = "other", tiles = {"GunshopCounters_20", "GunshopCounters_28"} }}
overlayMap["GunshopCounters_13"] = {{ name = "other", tiles = {"GunshopCounters_21", "GunshopCounters_29"} }}
overlayMap["GunshopCounters_14"] = {{ name = "other", tiles = {"GunshopCounters_22", "GunshopCounters_30"} }}
overlayMap["GunshopCounters_15"] = {{ name = "other", tiles = {"GunshopCounters_23", "GunshopCounters_31"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
